//! Pure reference-page rendering for linked and runtime-owned verb handles.
//!
//! Hosts pass an explicitly initialized registry's handles to [`render`]
//! and choose the output directory. This module never opens a store, reads
//! environment credentials, or probes a provider.

use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;

use impress_service_core::VerbHandle;
use serde_json::Value;

/// Markdown-escape a string for use inside a table cell (pipes and
/// newlines, the two things that break a Markdown table row).
fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

fn render_service(service: &str, verbs: &[VerbHandle]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {service}\n\n"));
    out.push_str(
        "Generated by `cargo run -p impress-capabilities --bin gen-verb-docs`. \
         Do not hand-edit — `scripts/check-verb-docs.sh` regenerates this file \
         and fails CI on a diff.\n\n",
    );
    for v in verbs {
        out.push_str(&format!("## `{}`\n\n", v.name()));
        out.push_str(v.description().trim());
        out.push_str("\n\n");
        if let VerbHandle::Provider(provider) = v {
            out.push_str(&format!(
                "- **source**: provider `{}` ({})\n",
                provider.provider_id,
                if provider.deprecated_since.is_some() {
                    "deprecated"
                } else if provider.status == impress_service_core::ProviderStatus::Available {
                    "available"
                } else {
                    "unavailable"
                }
            ));
            out.push_str(&format!(
                "- **declared safety**: `{}`\n",
                provider.declared_safety.class.as_str()
            ));
            if let Some(since) = &provider.deprecated_since {
                out.push_str(&format!(
                    "- **deprecated** since `{since}`: provider no longer advertises this verb\n"
                ));
            }
        }
        let safety = v.safety();
        let effects = v.effects();
        out.push_str(&format!(
            "- **safety**: `{}`{}\n",
            safety.class.as_str(),
            if safety.idempotent {
                ", idempotent"
            } else {
                ""
            }
        ));
        if let Some(budget_ms) = v.budget_ms() {
            out.push_str(&format!(
                "- **budget**: `{budget_ms}ms` — a Tier A example that exceeds it \
                 (with CI slack) fails the run\n"
            ));
        }
        if let Some(linked) = v.linked() {
            if let Some(dep) = linked.deprecated {
                if linked.aliases.is_empty() {
                    out.push_str(&format!(
                        "- **deprecated** since `{}`: {}\n",
                        dep.since, dep.note
                    ));
                }
            }
            if !linked.aliases.is_empty() {
                let names: Vec<String> = linked.aliases.iter().map(|a| format!("`{a}`")).collect();
                out.push_str(&format!(
                    "- **aliases** (deprecated since `{}`; still callable, never listed): {}\n",
                    linked.deprecated.map(|d| d.since).unwrap_or("—"),
                    names.join(", ")
                ));
            }
        }
        out.push_str(&format!(
            "- **reads**: {}\n",
            if effects.reads.is_empty() {
                "—".to_string()
            } else {
                effects
                    .reads
                    .iter()
                    .map(|k| k.describe())
                    .collect::<Vec<_>>()
                    .join(", ")
            }
        ));
        out.push_str(&format!(
            "- **writes**: {}\n",
            if effects.writes.is_empty() {
                "—".to_string()
            } else {
                effects
                    .writes
                    .iter()
                    .map(|k| k.describe())
                    .collect::<Vec<_>>()
                    .join(", ")
            }
        ));
        out.push_str(&format!(
            "- **reach**: {}\n",
            if effects.reach.is_empty() {
                "—".to_string()
            } else {
                effects
                    .reach
                    .iter()
                    .map(|r| r.describe())
                    .collect::<Vec<_>>()
                    .join(", ")
            }
        ));
        out.push('\n');

        let schema = v.input_schema();
        let props = schema
            .get("properties")
            .and_then(Value::as_object)
            .cloned()
            .unwrap_or_default();
        if props.is_empty() {
            out.push_str("Takes no arguments.\n\n");
        } else {
            let required: Vec<String> = schema
                .get("required")
                .and_then(Value::as_array)
                .map(|a| {
                    a.iter()
                        .filter_map(|v| v.as_str().map(str::to_string))
                        .collect()
                })
                .unwrap_or_default();
            out.push_str("| Argument | Type | Required | Description |\n");
            out.push_str("|---|---|---|---|\n");
            for (name, prop) in &props {
                let ty = prop
                    .get("type")
                    .and_then(Value::as_str)
                    .unwrap_or("—")
                    .to_string();
                let req = if required.contains(name) { "yes" } else { "no" };
                let desc = prop
                    .get("description")
                    .and_then(Value::as_str)
                    .unwrap_or("*(undocumented)*");
                out.push_str(&format!(
                    "| `{}` | {} | {} | {} |\n",
                    cell(name),
                    cell(&ty),
                    req,
                    cell(desc)
                ));
            }
            out.push('\n');
        }

        let examples = v.examples();
        if examples.is_empty() {
            out.push_str("_No examples yet._\n\n");
        } else {
            out.push_str("**Examples**\n\n");
            for ex in examples {
                let tier = match ex.tier {
                    impress_service_core::ExampleTier::A => "A",
                    impress_service_core::ExampleTier::B => "B (isolated host)",
                };
                out.push_str(&format!("- `{}` — Tier {tier}:\n\n", ex.name));
                out.push_str("  ```json\n");
                out.push_str(&format!("  {}\n", ex.args));
                out.push_str("  ```\n");
                if let Some(expect) = ex.expect {
                    out.push_str("  expects:\n\n  ```json\n");
                    out.push_str(&format!("  {expect}\n"));
                    out.push_str("  ```\n");
                }
                out.push('\n');
            }
        }
    }
    out
}

/// Missing reference information, reported before the checked-in generator
/// writes any pages. Runtime hosts may still preview an incomplete provider's
/// metadata with `render`; publishing the linked reference requires completeness.
pub fn documentation_problems<'a>(
    handles: impl IntoIterator<Item = &'a VerbHandle>,
) -> Vec<String> {
    let mut problems = Vec::new();
    for verb in handles {
        if verb.examples().is_empty() {
            problems.push(format!("{} has no example", verb.name()));
        }
        if let Some(properties) = verb
            .input_schema()
            .get("properties")
            .and_then(Value::as_object)
        {
            for (name, property) in properties {
                if property
                    .get("description")
                    .and_then(Value::as_str)
                    .is_none_or(|doc| doc.trim().is_empty())
                {
                    problems.push(format!(
                        "{} argument {name} has no description",
                        verb.name()
                    ));
                }
            }
        }
    }
    problems.sort();
    problems
}

/// A complete set of pages, including the index, ready to write to an owned
/// directory. Keeping rendering separate from I/O lets hosts preview output.
pub struct RenderedVerbDocs {
    pub pages: BTreeMap<String, String>,
    pub index: String,
}

impl RenderedVerbDocs {
    /// Write pages and README to `out_dir`. Existing unrelated files are
    /// untouched; the checked-in generator performs its own stale-page prune.
    pub fn write_to_dir(&self, out_dir: &Path) -> io::Result<usize> {
        for service in self.pages.keys() {
            if !valid_service_filename(service) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "unsafe service page name",
                ));
            }
        }
        fs::create_dir_all(out_dir)?;
        for (service, page) in &self.pages {
            fs::write(out_dir.join(format!("{service}.md")), page)?;
        }
        fs::write(out_dir.join("README.md"), &self.index)?;
        Ok(self.pages.len())
    }
}

fn valid_service_filename(service: &str) -> bool {
    !service.is_empty()
        && service
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
}

/// Render exactly the handles supplied by a caller. The standalone binary
/// passes only linked handles; an initialized host may pass its unified
/// registry to obtain provider pages without making this kit open a store.
pub fn render(handles: impl IntoIterator<Item = VerbHandle>) -> RenderedVerbDocs {
    let mut by_service: BTreeMap<String, Vec<VerbHandle>> = BTreeMap::new();
    let mut includes_providers = false;
    for verb in handles {
        includes_providers |= matches!(verb, VerbHandle::Provider(_));
        by_service
            .entry(verb.service().to_string())
            .or_default()
            .push(verb);
    }
    for verbs in by_service.values_mut() {
        verbs.sort_by(|a, b| a.name().cmp(b.name()));
    }
    let mut pages = BTreeMap::new();
    let mut index = String::new();
    index.push_str("# Verb reference\n\n");
    if includes_providers {
        index.push_str(
            "One page per service, generated from linked descriptors and the host's explicitly loaded runtime providers.\n\n",
        );
    } else {
        index.push_str(
            "One page per service, generated from the linked `VerbDescriptor` \
             inventory. Regenerate with `cargo run -p impress-capabilities \
             --bin gen-verb-docs`; `scripts/check-verb-docs.sh` fails CI on a \
             diff.\n\n",
        );
    }
    for (service, verbs) in &by_service {
        pages.insert(service.clone(), render_service(service, verbs));
        index.push_str(&format!(
            "- [{service}]({service}.md) ({} verbs)\n",
            verbs.len()
        ));
    }
    RenderedVerbDocs { pages, index }
}

#[cfg(test)]
mod tests {
    use super::*;
    use impress_service_core::{ProviderStatus, ProviderVerb, Safety, SafetyClass};
    use serde_json::json;
    use std::sync::Arc;

    #[test]
    fn owned_provider_page_keeps_source_and_effective_safety() {
        let handle = VerbHandle::Provider(Arc::new(ProviderVerb {
            name: "fixture-service_echo".into(),
            service: "fixture-service".into(),
            method: "echo".into(),
            description: "Echo text".into(),
            input_schema: json!({"type":"object","properties":{"text":{"type":"string","description":"Text to echo"}},"required":["text"],"additionalProperties":false}),
            output_schema: json!({"type":"object"}),
            declared_safety: Safety {
                class: SafetyClass::ReadOnly,
                idempotent: true,
            },
            effective_safety: Safety {
                class: SafetyClass::External,
                idempotent: false,
            },
            since: "0.1.0".into(),
            examples: vec![impress_service_core::ProviderExample {
                name: "hello".into(),
                args: r#"{"text":"hello"}"#.into(),
                expect: Some(r#"{"echo":"hello"}"#.into()),
            }],
            provider_id: "fixture".into(),
            status: ProviderStatus::Unavailable,
            deprecated_since: None,
            generation: 1,
        }));
        let docs = render([handle]);
        let page = &docs.pages["fixture-service"];
        assert!(page.contains("**source**: provider `fixture` (unavailable)"));
        assert!(page.contains("**declared safety**: `read_only`"));
        assert!(page.contains("**safety**: `external`"));
        assert!(page.contains("| `text` | string | yes | Text to echo |"));
        assert!(page.contains(r#"{"text":"hello"}"#));
        assert!(docs.index.contains("runtime providers"));
    }

    #[test]
    fn rendered_page_names_cannot_escape_output_directory() {
        assert!(valid_service_filename("fixture-service"));
        assert!(!valid_service_filename("../fixture"));
        assert!(!valid_service_filename("fixture/service"));
    }
}
