// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(impress_store_ffiFFI)
import impress_store_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_impress_store_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_impress_store_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A handle to the shared impress-core SQLite database.
 *
 * Construct with `SharedStore.open(path:)` or `SharedStore.openInMemory()`.
 * The handle is thread-safe (`Sync + Send`) via the underlying `SqliteItemStore`.
 */
public protocol SharedStoreProtocol : AnyObject {
    
    /**
     * Add a hierarchical tag to an item (e.g. `"methods/sims/hydro"`).
     */
    func addTag(id: String, tag: String) throws 
    
    /**
     * Delete an item by ID.
     *
     * Returns `NotFound` if no item with `id` exists.
     */
    func deleteItem(id: String) throws 
    
    /**
     * Retrieve a single item by ID, or `nil` if not found.
     */
    func getItem(id: String) throws  -> SharedItemRow?
    
    /**
     * List items by schema, sorted by creation time (newest first).
     *
     * - `schema_ref`: e.g. `"bibliography-entry"`.
     * - `limit`: Maximum number of results (0 = default of 100).
     * - `offset`: Pagination offset.
     */
    func queryBySchema(schemaRef: String, limit: UInt32, offset: UInt32) throws  -> [SharedItemRow]
    
    /**
     * Remove a tag from an item.
     */
    func removeTag(id: String, tag: String) throws 
    
    /**
     * Full-text search across all items, with optional schema filter.
     *
     * Searches the FTS5 index (title, author_text, abstract_text, note fields).
     * Matches items where any of those fields contains `query`.
     */
    func search(query: String, schemaFilter: String?, limit: UInt32) throws  -> [SharedItemRow]
    
    /**
     * Set or clear a flag on an item.
     *
     * Pass `None` for `color` to clear the flag entirely.
     * `style` and `length` are optional refinements (e.g. "dashed", "half").
     */
    func setFlag(id: String, color: String?, style: String?, length: String?) throws 
    
    /**
     * Mark an item as read or unread.
     */
    func setRead(id: String, isRead: Bool) throws 
    
    /**
     * Mark an item as starred or unstarred.
     */
    func setStarred(id: String, isStarred: Bool) throws 
    
    /**
     * Insert or update an item.
     *
     * - `id`: Stable UUID string (use the app-domain item ID for idempotency).
     * - `schema_ref`: Schema identifier, e.g. `"bibliography-entry"`.
     * - `payload_json`: JSON object with domain-specific fields.
     *
     * If an item with `id` already exists, its payload fields are updated
     * to match `payload_json`. Fields not present in `payload_json` are left
     * unchanged (additive semantics, not replace-all).
     */
    func upsertItem(id: String, schemaRef: String, payloadJson: String) throws 
    
}

/**
 * A handle to the shared impress-core SQLite database.
 *
 * Construct with `SharedStore.open(path:)` or `SharedStore.openInMemory()`.
 * The handle is thread-safe (`Sync + Send`) via the underlying `SqliteItemStore`.
 */
open class SharedStore:
    SharedStoreProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_impress_store_ffi_fn_clone_sharedstore(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_impress_store_ffi_fn_free_sharedstore(pointer, $0) }
    }

    
    /**
     * Open (or create) the shared impress-core database at `path`.
     *
     * Call `SharedWorkspace.ensureDirectoryExists()` before opening to ensure
     * the parent directory exists. Safe to call from multiple processes — SQLite
     * WAL mode provides concurrent-reader, exclusive-writer access.
     */
public static func `open`(path: String)throws  -> SharedStore {
    return try  FfiConverterTypeSharedStore.lift(try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_constructor_sharedstore_open(
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Open an ephemeral in-memory store. Intended for unit tests only.
     */
public static func openInMemory()throws  -> SharedStore {
    return try  FfiConverterTypeSharedStore.lift(try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_constructor_sharedstore_open_in_memory($0
    )
})
}
    

    
    /**
     * Add a hierarchical tag to an item (e.g. `"methods/sims/hydro"`).
     */
open func addTag(id: String, tag: String)throws  {try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_add_tag(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(tag),$0
    )
}
}
    
    /**
     * Delete an item by ID.
     *
     * Returns `NotFound` if no item with `id` exists.
     */
open func deleteItem(id: String)throws  {try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_delete_item(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Retrieve a single item by ID, or `nil` if not found.
     */
open func getItem(id: String)throws  -> SharedItemRow? {
    return try  FfiConverterOptionTypeSharedItemRow.lift(try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_get_item(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * List items by schema, sorted by creation time (newest first).
     *
     * - `schema_ref`: e.g. `"bibliography-entry"`.
     * - `limit`: Maximum number of results (0 = default of 100).
     * - `offset`: Pagination offset.
     */
open func queryBySchema(schemaRef: String, limit: UInt32, offset: UInt32)throws  -> [SharedItemRow] {
    return try  FfiConverterSequenceTypeSharedItemRow.lift(try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_query_by_schema(self.uniffiClonePointer(),
        FfiConverterString.lower(schemaRef),
        FfiConverterUInt32.lower(limit),
        FfiConverterUInt32.lower(offset),$0
    )
})
}
    
    /**
     * Remove a tag from an item.
     */
open func removeTag(id: String, tag: String)throws  {try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_remove_tag(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(tag),$0
    )
}
}
    
    /**
     * Full-text search across all items, with optional schema filter.
     *
     * Searches the FTS5 index (title, author_text, abstract_text, note fields).
     * Matches items where any of those fields contains `query`.
     */
open func search(query: String, schemaFilter: String?, limit: UInt32)throws  -> [SharedItemRow] {
    return try  FfiConverterSequenceTypeSharedItemRow.lift(try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterOptionString.lower(schemaFilter),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
    /**
     * Set or clear a flag on an item.
     *
     * Pass `None` for `color` to clear the flag entirely.
     * `style` and `length` are optional refinements (e.g. "dashed", "half").
     */
open func setFlag(id: String, color: String?, style: String?, length: String?)throws  {try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_set_flag(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterOptionString.lower(color),
        FfiConverterOptionString.lower(style),
        FfiConverterOptionString.lower(length),$0
    )
}
}
    
    /**
     * Mark an item as read or unread.
     */
open func setRead(id: String, isRead: Bool)throws  {try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_set_read(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterBool.lower(isRead),$0
    )
}
}
    
    /**
     * Mark an item as starred or unstarred.
     */
open func setStarred(id: String, isStarred: Bool)throws  {try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_set_starred(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterBool.lower(isStarred),$0
    )
}
}
    
    /**
     * Insert or update an item.
     *
     * - `id`: Stable UUID string (use the app-domain item ID for idempotency).
     * - `schema_ref`: Schema identifier, e.g. `"bibliography-entry"`.
     * - `payload_json`: JSON object with domain-specific fields.
     *
     * If an item with `id` already exists, its payload fields are updated
     * to match `payload_json`. Fields not present in `payload_json` are left
     * unchanged (additive semantics, not replace-all).
     */
open func upsertItem(id: String, schemaRef: String, payloadJson: String)throws  {try rustCallWithError(FfiConverterTypeSharedStoreError.lift) {
    uniffi_impress_store_ffi_fn_method_sharedstore_upsert_item(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(schemaRef),
        FfiConverterString.lower(payloadJson),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSharedStore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SharedStore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SharedStore {
        return SharedStore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SharedStore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SharedStore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SharedStore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSharedStore_lift(_ pointer: UnsafeMutableRawPointer) throws -> SharedStore {
    return try FfiConverterTypeSharedStore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSharedStore_lower(_ value: SharedStore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSharedStore.lower(value)
}


/**
 * A flat representation of a single item, suitable for Swift consumption.
 *
 * `payload_json` is a JSON object string containing domain-specific fields.
 * Parse it in Swift with `JSONDecoder` using the schema-specific payload type.
 */
public struct SharedItemRow {
    public var id: String
    public var schemaRef: String
    public var payloadJson: String
    /**
     * Item creation timestamp in milliseconds since Unix epoch.
     */
    public var createdMs: Int64
    public var isRead: Bool
    public var isStarred: Bool
    public var tags: [String]
    /**
     * Flag color if the item is flagged (e.g. "red", "amber", "blue", "gray").
     */
    public var flagColor: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, schemaRef: String, payloadJson: String, 
        /**
         * Item creation timestamp in milliseconds since Unix epoch.
         */createdMs: Int64, isRead: Bool, isStarred: Bool, tags: [String], 
        /**
         * Flag color if the item is flagged (e.g. "red", "amber", "blue", "gray").
         */flagColor: String?) {
        self.id = id
        self.schemaRef = schemaRef
        self.payloadJson = payloadJson
        self.createdMs = createdMs
        self.isRead = isRead
        self.isStarred = isStarred
        self.tags = tags
        self.flagColor = flagColor
    }
}



extension SharedItemRow: Equatable, Hashable {
    public static func ==(lhs: SharedItemRow, rhs: SharedItemRow) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.schemaRef != rhs.schemaRef {
            return false
        }
        if lhs.payloadJson != rhs.payloadJson {
            return false
        }
        if lhs.createdMs != rhs.createdMs {
            return false
        }
        if lhs.isRead != rhs.isRead {
            return false
        }
        if lhs.isStarred != rhs.isStarred {
            return false
        }
        if lhs.tags != rhs.tags {
            return false
        }
        if lhs.flagColor != rhs.flagColor {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(schemaRef)
        hasher.combine(payloadJson)
        hasher.combine(createdMs)
        hasher.combine(isRead)
        hasher.combine(isStarred)
        hasher.combine(tags)
        hasher.combine(flagColor)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSharedItemRow: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SharedItemRow {
        return
            try SharedItemRow(
                id: FfiConverterString.read(from: &buf), 
                schemaRef: FfiConverterString.read(from: &buf), 
                payloadJson: FfiConverterString.read(from: &buf), 
                createdMs: FfiConverterInt64.read(from: &buf), 
                isRead: FfiConverterBool.read(from: &buf), 
                isStarred: FfiConverterBool.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                flagColor: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SharedItemRow, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.schemaRef, into: &buf)
        FfiConverterString.write(value.payloadJson, into: &buf)
        FfiConverterInt64.write(value.createdMs, into: &buf)
        FfiConverterBool.write(value.isRead, into: &buf)
        FfiConverterBool.write(value.isStarred, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterOptionString.write(value.flagColor, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSharedItemRow_lift(_ buf: RustBuffer) throws -> SharedItemRow {
    return try FfiConverterTypeSharedItemRow.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSharedItemRow_lower(_ value: SharedItemRow) -> RustBuffer {
    return FfiConverterTypeSharedItemRow.lower(value)
}


/**
 * Errors returned by the shared store FFI.
 */
public enum SharedStoreError {

    
    
    case NotFound(message: String
    )
    case AlreadyExists(message: String
    )
    case InvalidArgument(message: String
    )
    case Storage(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSharedStoreError: FfiConverterRustBuffer {
    typealias SwiftType = SharedStoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SharedStoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .AlreadyExists(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidArgument(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Storage(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SharedStoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .NotFound(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .AlreadyExists(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidArgument(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Storage(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension SharedStoreError: Equatable, Hashable {}

extension SharedStoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSharedItemRow: FfiConverterRustBuffer {
    typealias SwiftType = SharedItemRow?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSharedItemRow.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSharedItemRow.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSharedItemRow: FfiConverterRustBuffer {
    typealias SwiftType = [SharedItemRow]

    public static func write(_ value: [SharedItemRow], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSharedItemRow.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SharedItemRow] {
        let len: Int32 = try readInt(&buf)
        var seq = [SharedItemRow]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSharedItemRow.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_impress_store_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_add_tag() != 31254) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_delete_item() != 14439) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_get_item() != 16629) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_query_by_schema() != 32264) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_remove_tag() != 18835) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_search() != 42949) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_set_flag() != 6264) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_set_read() != 9862) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_set_starred() != 29104) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_method_sharedstore_upsert_item() != 18542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_constructor_sharedstore_open() != 6376) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_impress_store_ffi_checksum_constructor_sharedstore_open_in_memory() != 51392) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all