name: impel
options:
  bundleIdPrefix: com.impress
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  developmentLanguage: en

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: impel
    DEVELOPMENT_TEAM: "${DEVELOPMENT_TEAM}"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic

packages:
  ImpelCore:
    path: Packages/ImpelCore
  ImpelMail:
    path: Packages/ImpelMail
  CounselEngine:
    path: Packages/CounselEngine
  ImpressAI:
    path: ../../packages/ImpressAI
  ImpressTestKit:
    path: ../../packages/ImpressTestKit
  ImpressKit:
    path: ../../packages/ImpressKit

targets:
  impel:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Shared
        excludes:
          - "**/*.xcassets"
      - path: macOS
        excludes:
          - "**/*.xcassets"
      - path: Shared/Assets.xcassets
      - path: macOS/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.impress.impel
        INFOPLIST_FILE: macOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: macOS/impel.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
    dependencies:
      - package: ImpelCore
      - package: ImpelMail
      - package: CounselEngine
      - package: ImpressAI
      - package: ImpressKit
    info:
      path: macOS/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.impress.impel
            CFBundleURLSchemes:
              - impel
        LSApplicationQueriesSchemes:
          - imbib
          - imprint
          - implore
          - impart
        UTImportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Paper Reference
            UTTypeIdentifier: com.impress.paper-reference
            UTTypeTagSpecification: {}
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Document Reference
            UTTypeIdentifier: com.impress.document-reference
            UTTypeTagSpecification: {}
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Figure Reference
            UTTypeIdentifier: com.impress.figure-reference
            UTTypeTagSpecification: {}
    entitlements:
      path: macOS/impel.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.security.application-groups:
          - group.com.impress.suite

  impelTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: impel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.impress.impel.tests
        PRODUCT_MODULE_NAME: impelTests
        GENERATE_INFOPLIST_FILE: YES

  impelUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: impelUITests
    dependencies:
      - target: impel
      - package: ImpressTestKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.impress.impel.uitests
        PRODUCT_MODULE_NAME: impelUITests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  impel:
    build:
      targets:
        impel: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - impelTests
        - impelUITests
    profile:
      config: Release
    archive:
      config: Release
