name: implore
options:
  bundleIdPrefix: com.impress.implore
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top
  developmentLanguage: en

settings:
  base:
    PRODUCT_NAME: implore
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    ENABLE_HARDENED_RUNTIME: YES
    DEVELOPMENT_TEAM: QG3MEYVHMS
    CODE_SIGN_STYLE: Automatic

packages:
  ImploreRustCore:
    path: ImploreRustCore
  ImploreCore:
    path: Packages/ImploreCore
  ImpressTestKit:
    path: ../../packages/ImpressTestKit
  ImpressHelixCore:
    path: ../../packages/ImpressHelixCore
  ImpressAutomation:
    path: ../../packages/ImpressAutomation
  ImpressLogging:
    path: ../../packages/ImpressLogging
  ImpressKit:
    path: ../../packages/ImpressKit
  ImpressKeyboard:
    path: ../../packages/ImpressKeyboard

targets:
  implore:
    type: application
    platform: macOS
    sources:
      - path: Implore/Sources
        excludes:
          - "**/.DS_Store"
          - "**/AI/**"
          - "**/Metal/**"
    settings:
      base:
        INFOPLIST_FILE: Implore/Info.plist
        CODE_SIGN_ENTITLEMENTS: Implore/implore.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.impress.implore
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/../../Frameworks"
    dependencies:
      - package: ImploreCore
      - package: ImpressHelixCore
      - package: ImpressAutomation
      - package: ImpressLogging
      - package: ImpressKit
      - package: ImpressKeyboard
    info:
      path: Implore/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: implore
            CFBundleURLSchemes:
              - implore
        LSApplicationQueriesSchemes:
          - imbib
          - imprint
          - impel
          - impart
        UTExportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Figure Reference
            UTTypeIdentifier: com.impress.figure-reference
            UTTypeTagSpecification: {}
    entitlements:
      path: Implore/implore.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.security.application-groups:
          - group.com.impress.shared
          - group.com.impress.suite

  imploreUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: imploreUITests
    dependencies:
      - target: implore
      - package: ImpressTestKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.impress.implore.uitests
        PRODUCT_MODULE_NAME: imploreUITests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  implore:
    build:
      targets:
        implore: all
        imploreUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - imploreUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
