//
//  Exports.swift
//  ImploreRustCore
//
//  Re-exports the Rust-generated types for use by the implore application.
//
//  All types from implore_core.swift are automatically public and available
//  when importing ImploreRustCore.
//
//  Available types include:
//
//  Data Types:
//  - Dataset, DatasetSource, DataSchema, DatasetMetadata
//  - FieldDescriptor, DataType, DataProvenance
//
//  View State:
//  - ViewState, Camera3D, CameraProjection
//  - Colormap, ColormapPreset, SelectionBounds
//  - RenderMode, AxisConfig, ShaderValue
//
//  Session Management:
//  - SessionFigure, FigureExport, FigureFormat
//
//  Vector Types (UniFFI-compatible):
//  - Vec2f, Vec3f, Vec4f, Vec3d, ColorRgb
//
//  Plugin System:
//  - PluginInfo, PluginCapability, GeneratorInfo, GeneratorParameter
//
//  Automation:
//  - AutomationUrl, AutomationAction
//

import Foundation

// The implore_core.swift file generated by UniFFI contains all the Swift types
// and functions. All public types are automatically exported when importing
// the ImploreRustCore module.
