//
//  Exports.swift
//  ImbibRustCore
//
//  Re-exports the Rust-generated types for use by PublicationManagerCore.
//
//  All types from imbib_core.swift are automatically public and available
//  when importing ImbibRustCore.
//
//  Available types include:
//
//  Domain Models:
//  - Publication, Author, Library, Tag, Collection
//  - SearchResult, LinkedFile, Identifiers, PdfLink
//  - ValidationError
//
//  BibTeX/RIS:
//  - BibTeXEntry, BibTeXField, BibTeXParseResult, BibTeXParseError
//  - RisEntry, RisTag, BibTeXEntryType, RisType
//
//  Import/Export:
//  - ImportResult, ImportFormat, ImportError
//  - ExportOptions, ExportFormat
//  - FilenameOptions
//
//  Deduplication:
//  - DeduplicationMatch, DuplicateGroup
//
//  Merge/Conflict:
//  - MergeResult, Conflict, MergeStrategy
//
//  Identifiers:
//  - ExtractedIdentifier
//
//  Enums:
//  - Source, ValidationSeverity, FileStorageType, PdfLinkType
//  - AdsDatabase, QueryLogic, ParseError
//

import Foundation

// The imbib_core.swift file generated by UniFFI contains all the Swift types
// and functions. All public types are automatically exported when importing
// the ImbibRustCore module.
