#!/bin/bash
# Build script for imprint Rust dependencies
#
# This script builds the imprint-core Rust library and generates:
# 1. Universal binary for macOS (arm64 + x86_64)
# 2. Swift bindings via UniFFI
# 3. XCFramework for Xcode integration
#
# Prerequisites:
# - Rust toolchain (rustup)
# - Xcode command line tools
# - cargo-lipo (for universal binaries)
#
# Usage: ./build-rust.sh [debug|release]

set -e

# Configuration
BUILD_TYPE="${1:-release}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RUST_CRATE="$WORKSPACE_ROOT/crates/imprint-core"
OUTPUT_DIR="$SCRIPT_DIR/Packages/ImprintCore"
FRAMEWORK_NAME="ImprintCoreFFI"

echo "Building imprint-core ($BUILD_TYPE)..."
echo "Workspace: $WORKSPACE_ROOT"
echo "Rust crate: $RUST_CRATE"
echo "Output: $OUTPUT_DIR"

# Verify Rust crate exists
if [ ! -f "$RUST_CRATE/Cargo.toml" ]; then
    echo "Error: imprint-core not found at $RUST_CRATE"
    exit 1
fi

# Build for macOS
echo ""
echo "=== Building for macOS ==="

cd "$RUST_CRATE"

if [ "$BUILD_TYPE" = "release" ]; then
    CARGO_FLAGS="--release"
    BUILD_DIR="release"
else
    CARGO_FLAGS=""
    BUILD_DIR="debug"
fi

# Build for macOS targets
echo "Building for aarch64-apple-darwin..."
cargo build $CARGO_FLAGS --target aarch64-apple-darwin --features uniffi

echo "Building for x86_64-apple-darwin..."
cargo build $CARGO_FLAGS --target x86_64-apple-darwin --features uniffi

# Create universal binary
echo ""
echo "=== Creating universal binary ==="

TARGETS_DIR="$WORKSPACE_ROOT/target"
AARCH64_LIB="$TARGETS_DIR/aarch64-apple-darwin/$BUILD_DIR/libimprint_core.a"
X86_64_LIB="$TARGETS_DIR/x86_64-apple-darwin/$BUILD_DIR/libimprint_core.a"
UNIVERSAL_DIR="$TARGETS_DIR/universal-macos-$BUILD_DIR"
UNIVERSAL_LIB="$UNIVERSAL_DIR/libimprint_core.a"

mkdir -p "$UNIVERSAL_DIR"

lipo -create \
    "$AARCH64_LIB" \
    "$X86_64_LIB" \
    -output "$UNIVERSAL_LIB"

echo "Universal library: $UNIVERSAL_LIB"

# Generate Swift bindings
echo ""
echo "=== Generating Swift bindings ==="

BINDINGS_DIR="$OUTPUT_DIR/Sources/ImprintCore/Generated"
mkdir -p "$BINDINGS_DIR"

# Use uniffi-bindgen to generate Swift code
cargo run --features uniffi --bin uniffi-bindgen generate \
    --library "$AARCH64_LIB" \
    --language swift \
    --out-dir "$BINDINGS_DIR" 2>/dev/null || {
    echo "Note: uniffi-bindgen not available, using placeholder bindings"
    # Create placeholder if bindgen fails
    cat > "$BINDINGS_DIR/imprint_core.swift" << 'EOF'
// Placeholder Swift bindings
// Run uniffi-bindgen to generate real bindings
//
// cargo install uniffi_bindgen
// uniffi-bindgen generate --library libimprint_core.a --language swift --out-dir .

import Foundation

// Re-export types from ImprintCore.swift
// Real bindings will replace this file
EOF
}

# Create XCFramework
echo ""
echo "=== Creating XCFramework ==="

XCFRAMEWORK_DIR="$OUTPUT_DIR/$FRAMEWORK_NAME.xcframework"

# Remove old framework
rm -rf "$XCFRAMEWORK_DIR"

# Create framework structure
MACOS_FRAMEWORK_DIR="$UNIVERSAL_DIR/$FRAMEWORK_NAME.framework"
mkdir -p "$MACOS_FRAMEWORK_DIR/Headers"
mkdir -p "$MACOS_FRAMEWORK_DIR/Modules"

# Copy library
cp "$UNIVERSAL_LIB" "$MACOS_FRAMEWORK_DIR/$FRAMEWORK_NAME"

# Create module map
cat > "$MACOS_FRAMEWORK_DIR/Modules/module.modulemap" << EOF
framework module $FRAMEWORK_NAME {
    header "imprint_core.h"
    export *
}
EOF

# Copy header (if generated)
if [ -f "$BINDINGS_DIR/imprint_coreFFI.h" ]; then
    cp "$BINDINGS_DIR/imprint_coreFFI.h" "$MACOS_FRAMEWORK_DIR/Headers/imprint_core.h"
else
    # Create minimal header
    cat > "$MACOS_FRAMEWORK_DIR/Headers/imprint_core.h" << 'EOF'
// imprint_core.h - C header for imprint-core FFI
// Generated by build-rust.sh

#ifndef IMPRINT_CORE_H
#define IMPRINT_CORE_H

#include <stdint.h>
#include <stdbool.h>

// Placeholder - real header generated by UniFFI

#endif // IMPRINT_CORE_H
EOF
fi

# Create Info.plist
cat > "$MACOS_FRAMEWORK_DIR/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$FRAMEWORK_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>com.imbib.imprint.core</string>
    <key>CFBundleName</key>
    <string>$FRAMEWORK_NAME</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
</dict>
</plist>
EOF

# Create XCFramework
xcodebuild -create-xcframework \
    -framework "$MACOS_FRAMEWORK_DIR" \
    -output "$XCFRAMEWORK_DIR"

echo ""
echo "=== Build complete ==="
echo "XCFramework: $XCFRAMEWORK_DIR"
echo "Swift bindings: $BINDINGS_DIR"
echo ""
echo "Add to your Xcode project:"
echo "  1. Drag $FRAMEWORK_NAME.xcframework to your project"
echo "  2. Add the generated Swift files from $BINDINGS_DIR"
