name: imprint
options:
  bundleIdPrefix: com.imbib
  deploymentTarget:
    macOS: "26.0"
    iOS: "26.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  developmentLanguage: en
  groupSortPosition: top

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: imprint
    DEVELOPMENT_TEAM: QG3MEYVHMS
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic

packages:
  ImprintCore:
    path: Packages/ImprintCore
  ImprintRustCore:
    path: ImprintRustCore
  ImpressTestKit:
    path: ../../packages/ImpressTestKit
  ImpressHelixCore:
    path: ../../packages/ImpressHelixCore
  ImpressAI:
    path: ../../packages/ImpressAI
  ImpressAutomation:
    path: ../../packages/ImpressAutomation
  ImpressKeyboard:
    path: ../../packages/ImpressKeyboard
  ImpressOperationQueue:
    path: ../../packages/ImpressOperationQueue
  ImpressSidebar:
    path: ../../packages/ImpressSidebar
  ImpressLogging:
    path: ../../packages/ImpressLogging
  ImpressKit:
    path: ../../packages/ImpressKit

targets:
  imprint:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Shared
      - path: macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imbib.imprint
        INFOPLIST_FILE: macOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: macOS/imprint.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
    dependencies:
      - package: ImprintCore
      - package: ImprintRustCore
      - package: ImpressHelixCore
      - package: ImpressAI
      - package: ImpressAutomation
      - package: ImpressKeyboard
      - package: ImpressOperationQueue
      - package: ImpressSidebar
      - package: ImpressLogging
      - package: ImpressKit
    info:
      path: macOS/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.imbib.imprint
            CFBundleURLSchemes:
              - imprint
        NSUserActivityTypes:
          - com.imprint.editing-document
          - com.imprint.viewing-document
        LSApplicationQueriesSchemes:
          - imbib
          - implore
          - impel
          - impart
        UTExportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Document Reference
            UTTypeIdentifier: com.impress.document-reference
            UTTypeTagSpecification: {}
        UTImportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Paper Reference
            UTTypeIdentifier: com.impress.paper-reference
            UTTypeTagSpecification: {}
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Figure Reference
            UTTypeIdentifier: com.impress.figure-reference
            UTTypeTagSpecification: {}
    entitlements:
      path: macOS/imprint.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.files.bookmarks.app-scope: true
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.security.application-groups:
          - group.com.imbib.shared
          - group.com.impress.suite
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.imbib.shared
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.imbib.shared

  imprintTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: imprint
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imbib.imprint.tests
        PRODUCT_MODULE_NAME: imprintTests
        GENERATE_INFOPLIST_FILE: YES

  imprintUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: imprintUITests
    dependencies:
      - target: imprint
      - package: ImpressTestKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imbib.imprint.uitests
        PRODUCT_MODULE_NAME: imprintUITests
        GENERATE_INFOPLIST_FILE: YES

  # iOS Target
  imprint-iOS:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Shared
      - path: imprint-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imbib.imprint
        INFOPLIST_FILE: imprint-iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: imprint-iOS/imprint-iOS.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
    dependencies:
      - package: ImprintCore
      - package: ImprintRustCore
      - package: ImpressHelixCore
      - package: ImpressAI
      - package: ImpressAutomation
      - package: ImpressKeyboard
      - package: ImpressOperationQueue
      - package: ImpressSidebar
      - package: ImpressLogging
      - package: ImpressKit
      - target: imprint-ShareExtension
        embed: true
    info:
      path: imprint-iOS/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.imbib.imprint
            CFBundleURLSchemes:
              - imprint
        NSUserActivityTypes:
          - com.imprint.editing-document
          - com.imprint.viewing-document
        LSApplicationQueriesSchemes:
          - imbib
          - implore
          - impel
          - impart
        UTExportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Document Reference
            UTTypeIdentifier: com.impress.document-reference
            UTTypeTagSpecification: {}
        UTImportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Paper Reference
            UTTypeIdentifier: com.impress.paper-reference
            UTTypeTagSpecification: {}
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Impress Figure Reference
            UTTypeIdentifier: com.impress.figure-reference
            UTTypeTagSpecification: {}
    entitlements:
      path: imprint-iOS/imprint-iOS.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.imbib.shared
          - group.com.impress.suite
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.imbib.shared
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.imbib.shared

  imprint-ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: imprint-ShareExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imbib.imprint.share-extension
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: imprint-ShareExtension/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - sdk: UIKit.framework
      - sdk: UniformTypeIdentifiers.framework
    info:
      path: imprint-ShareExtension/Info.plist
    entitlements:
      path: imprint-ShareExtension/imprint-ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.impress.suite

  imprint-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: imprint-iOSTests
    dependencies:
      - target: imprint-iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.imbib.imprint.iostests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  imprint:
    build:
      targets:
        imprint: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - imprintTests
        - imprintUITests
    profile:
      config: Release
    archive:
      config: Release

  imprint-iOS:
    build:
      targets:
        imprint-iOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - imprint-iOSTests
    profile:
      config: Release
    archive:
      config: Release
