//
//  PDFMetadataExtractor.swift
//  PublicationManagerCore
//
//  Created by Claude on 2026-01-16.
//

import Foundation
import PDFKit
import OSLog
import ImbibRustCore

// MARK: - PDF Extracted Metadata

/// Metadata extracted from a PDF document.
public struct PDFExtractedMetadata: Sendable {
    /// Title from PDF document properties
    public let title: String?

    /// Author from PDF document properties
    public let author: String?

    /// Subject/description from PDF document properties
    public let subject: String?

    /// Keywords from PDF document properties
    public let keywords: [String]

    /// DOI extracted from PDF content
    public let extractedDOI: String?

    /// arXiv ID extracted from PDF content
    public let extractedArXivID: String?

    /// Bibcode extracted from PDF content (ADS)
    public let extractedBibcode: String?

    /// First-page text (fallback for title extraction)
    public let firstPageText: String?

    /// Confidence level of the extraction
    public let confidence: MetadataConfidence

    /// Creation date from PDF metadata
    public let creationDate: Date?

    /// Modification date from PDF metadata
    public let modificationDate: Date?

    // MARK: - Heuristically Extracted Fields

    /// Title extracted heuristically from PDF text
    public let heuristicTitle: String?

    /// Authors extracted heuristically from PDF text
    public let heuristicAuthors: [String]

    /// Year extracted heuristically from PDF text
    public let heuristicYear: Int?

    /// Journal extracted heuristically from PDF text
    public let heuristicJournal: String?

    /// Confidence of heuristic extraction
    public let heuristicConfidence: ImbibRustCore.HeuristicConfidence

    public init(
        title: String? = nil,
        author: String? = nil,
        subject: String? = nil,
        keywords: [String] = [],
        extractedDOI: String? = nil,
        extractedArXivID: String? = nil,
        extractedBibcode: String? = nil,
        firstPageText: String? = nil,
        confidence: MetadataConfidence = .none,
        creationDate: Date? = nil,
        modificationDate: Date? = nil,
        heuristicTitle: String? = nil,
        heuristicAuthors: [String] = [],
        heuristicYear: Int? = nil,
        heuristicJournal: String? = nil,
        heuristicConfidence: ImbibRustCore.HeuristicConfidence = .none
    ) {
        self.title = title
        self.author = author
        self.subject = subject
        self.keywords = keywords
        self.extractedDOI = extractedDOI
        self.extractedArXivID = extractedArXivID
        self.extractedBibcode = extractedBibcode
        self.firstPageText = firstPageText
        self.confidence = confidence
        self.creationDate = creationDate
        self.modificationDate = modificationDate
        self.heuristicTitle = heuristicTitle
        self.heuristicAuthors = heuristicAuthors
        self.heuristicYear = heuristicYear
        self.heuristicJournal = heuristicJournal
        self.heuristicConfidence = heuristicConfidence
    }

    /// Whether any identifier was extracted
    public var hasIdentifier: Bool {
        extractedDOI != nil || extractedArXivID != nil || extractedBibcode != nil
    }

    /// Best title: document properties → heuristic → first-page.
    ///
    /// The document's `titleAttribute` is *not* trusted blindly — many
    /// publisher PDFs have garbage there (PII codes like
    /// `"PII: 0360-1285(85)90002-4"`, LaTeX-export artifacts like
    /// `"Microsoft Word - manuscript.docx"`, or the string `"Untitled"`).
    /// When the document title fails `isPlausibleTitle`, we fall through
    /// to the heuristic title extracted from page 1 (usually correct) or
    /// the first-page text fragment.
    public var bestTitle: String? {
        Self.bestFields(of: self).bestTitle
    }

    /// Filter for PDF `titleAttribute` values that commonly leak through
    /// as junk from publisher templates or tooling.
    ///
    /// Rejects:
    ///   • Empty / whitespace-only / "Untitled" strings
    ///   • PII codes: `PII:…`, or bare `NNNN-NNNN(YY)NNNNNN-N`
    ///   • DOI-looking values: `doi:…`, `10.…/…`
    ///   • Autogenerated: `Microsoft Word - …`, `document1`, `manuscript`
    ///   • All-digits / all-punctuation strings
    ///   • Too short to be a title (< 6 visible chars)
    ///
    /// Stage 7 item 9: the predicate lives in `imbib-core`'s
    /// `pdf::is_plausible_title`, pinned by 23 golden cases.
    static func isPlausibleTitle(_ candidate: String) -> Bool {
        ImbibRustCore.pdfIsPlausibleTitle(candidate: candidate)
    }

    /// Best authors: document properties → heuristic.
    ///
    /// **Divergence (data integrity):** the old gate was `!author.isEmpty`
    /// UNTRIMMED, so an `authorAttribute` of `"   "` counted as "the PDF told us
    /// the authors"; the comma split produced one empty component, the filter
    /// dropped it, and this returned `[]` while `heuristicAuthors` held real
    /// names. Recovered author data discarded in favour of nothing. The Rust
    /// gate asks for visible content.
    public var bestAuthors: [String] {
        Self.bestFields(of: self).bestAuthors
    }

    /// Best year: heuristic (document properties don't typically have year).
    public var bestYear: Int? {
        heuristicYear
    }

    /// One FFI hop resolving `bestTitle` / `bestAuthors` / `bestYear` /
    /// `hasIdentifier` together, so the pure logic has a single definition.
    fileprivate static func bestFields(of metadata: PDFExtractedMetadata) -> FfiPdfBestFields {
        ImbibRustCore.pdfBestFields(
            fields: FfiPdfExtractedFields(
                title: metadata.title,
                author: metadata.author,
                heuristicTitle: metadata.heuristicTitle,
                heuristicAuthors: metadata.heuristicAuthors,
                heuristicYear: metadata.heuristicYear.map(Int32.init),
                firstPageText: metadata.firstPageText,
                extractedDoi: metadata.extractedDOI,
                extractedArxivId: metadata.extractedArXivID,
                extractedBibcode: metadata.extractedBibcode
            )
        )
    }
}

// MARK: - Metadata Confidence

/// Confidence level of extracted metadata.
public enum MetadataConfidence: Int, Comparable, Sendable {
    /// No metadata could be extracted
    case none = 0

    /// Low confidence (fallback methods, heuristics)
    case low = 1

    /// Medium confidence (document properties but incomplete)
    case medium = 2

    /// High confidence (complete document properties or verified identifier)
    case high = 3

    public static func < (lhs: MetadataConfidence, rhs: MetadataConfidence) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

// MARK: - PDF Metadata Extractor

/// Extracts metadata and identifiers from PDF documents.
///
/// Extraction phases:
/// 1. PDF document properties (title, author, subject, keywords)
/// 2. Content scan for DOI/arXiv identifiers
/// 3. First-page title extraction (fallback)
public actor PDFMetadataExtractor {

    // MARK: - Singleton

    public static let shared = PDFMetadataExtractor()

    // MARK: - Properties

    /// Maximum number of pages to scan for identifiers
    private let maxPagesToScan = 3

    /// Maximum characters to scan per page
    private let maxCharsPerPage = 10000

    // MARK: - Initialization

    public init() {}

    // MARK: - Public Methods

    /// Extract metadata from a PDF file.
    ///
    /// - Parameter url: URL of the PDF file
    /// - Returns: Extracted metadata, or nil if the file cannot be read
    public func extract(from url: URL) async -> PDFExtractedMetadata? {
        Logger.files.infoCapture("Extracting metadata from: \(url.lastPathComponent)", category: "files")

        // Load PDF document for document properties
        guard let document = PDFDocument(url: url) else {
            Logger.files.warningCapture("Could not load PDF: \(url.lastPathComponent)", category: "files")
            return nil
        }

        // Try pdfium for text extraction (faster), fall back to PDFKit
        var scannedText: String
        do {
            scannedText = try await extractTextViaPdfium(from: url, maxPages: maxPagesToScan)
            Logger.files.debugCapture("Used pdfium for text extraction", category: "files")
        } catch {
            Logger.files.debugCapture("pdfium extraction failed, falling back to PDFKit: \(error.localizedDescription)", category: "files")
            scannedText = await extractTextViaPDFKit(document, maxPages: maxPagesToScan)
        }

        return await extractFromDocument(document, preExtractedText: scannedText)
    }

    /// Extract metadata from PDF data.
    ///
    /// - Parameter data: PDF data
    /// - Returns: Extracted metadata, or nil if the data is invalid
    public func extract(from data: Data) async -> PDFExtractedMetadata? {
        Logger.files.infoCapture("Extracting metadata from PDF data (\(data.count) bytes)", category: "files")

        guard let document = PDFDocument(data: data) else {
            Logger.files.warningCapture("Could not parse PDF data", category: "files")
            return nil
        }

        return await extractFromDocument(document)
    }

    // MARK: - Private Methods

    /// Extract metadata from a loaded PDF document.
    ///
    /// - Parameters:
    ///   - document: PDFKit document
    ///   - preExtractedText: Pre-extracted text (from pdfium). If nil, extracts via PDFKit.
    @MainActor
    private func extractFromDocument(_ document: PDFDocument, preExtractedText: String? = nil) async -> PDFExtractedMetadata {
        var title: String?
        var author: String?
        var subject: String?
        var keywords: [String] = []
        var creationDate: Date?
        var modificationDate: Date?
        var extractedDOI: String?
        var extractedArXivID: String?
        var extractedBibcode: String?
        var firstPageText: String?
        var confidence: MetadataConfidence = .none

        // Phase 1: Extract document properties
        if let attributes = document.documentAttributes {
            title = attributes[PDFDocumentAttribute.titleAttribute] as? String
            author = attributes[PDFDocumentAttribute.authorAttribute] as? String
            subject = attributes[PDFDocumentAttribute.subjectAttribute] as? String

            if let keywordsAttr = attributes[PDFDocumentAttribute.keywordsAttribute] {
                if let keywordsArray = keywordsAttr as? [String] {
                    keywords = keywordsArray
                } else if let keywordsString = keywordsAttr as? String {
                    keywords = keywordsString.components(separatedBy: CharacterSet(charactersIn: ",;"))
                        .map { $0.trimmingCharacters(in: .whitespaces) }
                        .filter { !$0.isEmpty }
                }
            }

            creationDate = attributes[PDFDocumentAttribute.creationDateAttribute] as? Date
            modificationDate = attributes[PDFDocumentAttribute.modificationDateAttribute] as? Date

            // Update confidence based on document properties
            if title != nil && author != nil {
                confidence = .high
            } else if title != nil || author != nil {
                confidence = .medium
            }
        }

        // Phase 2: Scan content for identifiers
        // Use pre-extracted text if available, otherwise extract via PDFKit
        let scannedText: String
        if let preExtracted = preExtractedText {
            scannedText = preExtracted
        } else {
            scannedText = extractTextViaPDFKit(document, maxPages: maxPagesToScan)
        }

        // Extract first page text for title fallback (use first portion of scanned text)
        let firstPagePortion = String(scannedText.prefix(maxCharsPerPage))
        // Stage 7 item 9: `extractTitleFromFirstPage` was DELETED. It was a
        // drifted duplicate of `imbib-core`'s `metadata_heuristics::extract_title`
        // — run on this very same string, three lines below — and a strictly
        // worse one: its only author test was `" and "` plus four capitals, so a
        // comma-separated byline sailed through and the title came out with the
        // authors glued on. That is the most common real PDF shape.
        //
        // The field also did not hold what its name says: it held Swift's title
        // GUESS, and `PDFImportHandler` fed it to an ADS *abstract* query. It now
        // holds the first-page text, which is both what the name promises and
        // what `bestTitle`'s last-resort fallback should be.
        firstPageText = firstPagePortion.isEmpty ? nil : firstPagePortion

        // Extract identifiers from scanned text
        extractedDOI = IdentifierExtractor.extractDOIFromText(scannedText)
        extractedArXivID = IdentifierExtractor.extractArXivFromText(scannedText)
        extractedBibcode = IdentifierExtractor.extractBibcodeFromText(scannedText)

        // Upgrade confidence if identifier found
        if extractedDOI != nil || extractedArXivID != nil {
            confidence = max(confidence, .high)
        } else if extractedBibcode != nil {
            confidence = max(confidence, .medium)
        }

        // Phase 3: Heuristic extraction via Rust (fallback when no identifiers)
        let currentYear = Int32(Calendar.current.component(.year, from: Date()))
        let heuristicFields = extractMetadataHeuristics(firstPageText: firstPagePortion, currentYear: currentYear)

        Logger.files.infoCapture(
            "Extracted metadata - title: \(title ?? "none"), DOI: \(extractedDOI ?? "none"), arXiv: \(extractedArXivID ?? "none"), heuristic: \(heuristicFields.confidence)",
            category: "files"
        )

        return PDFExtractedMetadata(
            title: title,
            author: author,
            subject: subject,
            keywords: keywords,
            extractedDOI: extractedDOI,
            extractedArXivID: extractedArXivID,
            extractedBibcode: extractedBibcode,
            firstPageText: firstPageText,
            confidence: confidence,
            creationDate: creationDate,
            modificationDate: modificationDate,
            heuristicTitle: heuristicFields.title,
            heuristicAuthors: heuristicFields.authors,
            heuristicYear: heuristicFields.year.map { Int($0) },
            heuristicJournal: heuristicFields.journal,
            heuristicConfidence: heuristicFields.confidence
        )
    }

    // MARK: - Text Extraction

    /// Extract text from PDF using pdfium (Rust) for speed, with PDFKit fallback.
    ///
    /// - Parameters:
    ///   - url: URL of the PDF file
    ///   - maxPages: Maximum number of pages to extract (default: 3)
    /// - Returns: Extracted text from the specified pages
    private func extractTextViaPdfium(from url: URL, maxPages: Int = 3) async throws -> String {
        let result = try RustPDFService.extractText(from: url)
        // Join first N pages
        let pageTexts = result.pages.prefix(maxPages).map { $0.text }
        return pageTexts.joined(separator: "\n")
    }

    /// Extract text from PDF using PDFKit (fallback).
    ///
    /// - Parameters:
    ///   - document: PDFKit document
    ///   - maxPages: Maximum number of pages to extract
    /// - Returns: Extracted text
    @MainActor
    private func extractTextViaPDFKit(_ document: PDFDocument, maxPages: Int = 3) -> String {
        let pageCount = min(document.pageCount, maxPages)
        var text = ""

        for pageIndex in 0..<pageCount {
            guard let page = document.page(at: pageIndex),
                  let pageText = page.string else {
                continue
            }
            text += String(pageText.prefix(maxCharsPerPage)) + "\n"
        }

        return text
    }

}
