//
//  ThroughlineTests.swift
//  imprint
//
//  Tests for the throughline model (ADR-0016): Rust↔Swift parity vectors,
//  paragraph extraction, staleness derivation, anchor-map codability, and
//  the FileWrapper sidecar round-trip (including the opt-in invariant that
//  non-opted documents stay byte-identical).
//

import XCTest
import UniformTypeIdentifiers
@testable import imprint

final class ThroughlineTests: XCTestCase {

    // MARK: - Rust↔Swift parity (canonical side: crates/imprint-service)

    func testItemIDMatchesRustParityVector() {
        // Vector generated by Rust `Uuid::new_v5(THROUGHLINE_ID_NAMESPACE,
        // "6e2a0000-…::throughline")` — see throughline.rs.
        let doc = UUID(uuidString: "6e2a0000-0000-0000-0000-000000000000")!
        XCTAssertEqual(
            ThroughlineIdentity.itemID(documentID: doc).uuidString.lowercased(),
            "2410e2a2-fa90-5132-9ab4-39b1fccf48b6")
    }

    func testSha256MatchesKnownDigest() {
        // Same vector as Rust BlobStore::sha256_hex("hello").
        XCTAssertEqual(
            ThroughlineText.sha256Hex("hello"),
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824")
    }

    // MARK: - Paragraph extraction (transliteration parity)

    func testExtractsLabeledParagraphsInOrder() {
        let src = "= Title\n\nWe claim X. <tl-claim>\n\nUnlabeled prose.\n\nIt matters because Y.\n<tl-why>\n"
        let ps = ThroughlineText.extractParagraphs(src)
        XCTAssertEqual(ps.count, 2)
        XCTAssertEqual(ps[0].label, "tl-claim")
        XCTAssertEqual(ps[0].body, "We claim X.")
        XCTAssertEqual(ps[1].label, "tl-why")
        XCTAssertEqual(ps[1].body, "It matters because Y.")
    }

    func testDuplicateLabelsKeepFirst() {
        let ps = ThroughlineText.extractParagraphs("First. <tl-a>\n\nSecond. <tl-a>\n")
        XCTAssertEqual(ps.count, 1)
        XCTAssertEqual(ps[0].body, "First.")
    }

    func testIgnoresNonTLAngleTokens() {
        let ps = ThroughlineText.extractParagraphs(
            "Compare a < b and c > d. <not-a-label>\n\nReal. <tl-real>\n")
        XCTAssertEqual(ps.count, 1)
        XCTAssertEqual(ps[0].label, "tl-real")
    }

    func testScaffoldCommentLabelTokenIsNotAParagraph() {
        // The scaffold's "// … <tl-*> …" comment must not extract (parity
        // with Rust: '*' fails the label charset).
        let source = ThroughlineIdentity.scaffoldSource(title: "T")
        let ps = ThroughlineText.extractParagraphs(source)
        XCTAssertEqual(ps.map(\.label), ["tl-overview"])
    }

    // MARK: - Anchor map

    func testAnchorMapRoundTrip() throws {
        var map = ThroughlineAnchorMap(documentID: UUID())
        map.anchors["tl-claim"] = ThroughlineAnchorEntry(
            sectionKeys: ["intro"],
            manuscriptHashes: ["intro": "abc"],
            throughlineHash: "def")
        map.supporting = ["appendix"]
        let json = try map.serialize()
        let back = try ThroughlineAnchorMap.parse(json)
        XCTAssertEqual(map, back)
    }

    func testAnchorMapRejectsNewerVersion() {
        let json = #"{"version": 99, "document_id": "x", "anchors": {}, "supporting": []}"#
        XCTAssertThrowsError(try ThroughlineAnchorMap.parse(json))
    }

    // MARK: - Derivation (four states, ADR-0016 D5)

    func testDerivationFourStates() {
        let doc = UUID()
        let src = "P1. <tl-a>\n\nP2 edited. <tl-b>\n"
        let ps = ThroughlineText.extractParagraphs(src)

        var map = ThroughlineAnchorMap(documentID: doc)
        map.anchors["tl-a"] = ThroughlineAnchorEntry(
            sectionKeys: ["intro"],
            manuscriptHashes: ["intro": ThroughlineText.sha256Hex("intro body v1")],
            throughlineHash: ps[0].contentHash)
        map.anchors["tl-b"] = ThroughlineAnchorEntry(
            sectionKeys: ["results"],
            manuscriptHashes: ["results": "old-hash"],
            throughlineHash: "old-paragraph-hash")
        map.anchors["tl-c"] = ThroughlineAnchorEntry(
            sectionKeys: ["ghost"], manuscriptHashes: [:], throughlineHash: "x")

        let hashes = [
            "intro": ThroughlineText.sha256Hex("intro body v1"),
            "results": ThroughlineText.sha256Hex("results body v1"),
        ]
        let states = ThroughlineDerivation.anchorStates(
            map: map, sectionHashes: hashes, paragraphs: ps)
        let byLabel = Dictionary(uniqueKeysWithValues: states.map { ($0.label, $0) })
        XCTAssertEqual(byLabel["tl-a"]?.state, "synced")
        XCTAssertEqual(byLabel["tl-b"]?.state, "manuscript-ahead+throughline-ahead")
        XCTAssertEqual(byLabel["tl-c"]?.state, "broken")
        XCTAssertEqual(byLabel["tl-c"]?.missingParagraph, true)
        XCTAssertEqual(byLabel["tl-c"]?.broken, ["ghost"])
    }

    func testCoverageExcludesAnchoredAndSupporting() {
        var map = ThroughlineAnchorMap(documentID: UUID())
        map.anchors["tl-a"] = ThroughlineAnchorEntry(sectionKeys: ["intro", "results"])
        map.supporting = ["appendix"]
        XCTAssertEqual(
            ThroughlineDerivation.coverage(
                map: map, sectionKeys: ["intro", "methods", "results", "appendix"]),
            ["methods"])
    }

    func testSectionKeySlugs() {
        XCTAssertEqual(ThroughlineText.sectionKey(forHeading: "Introduction"), "introduction")
        XCTAssertEqual(
            ThroughlineText.sectionKey(forHeading: "Numerical Methods & Setup"),
            "numerical-methods-setup")
        XCTAssertEqual(ThroughlineText.sectionKey(forHeading: "  §3. Results!  "), "3-results")
        XCTAssertEqual(ThroughlineText.sectionKey(forHeading: "———"), "untitled")
    }

    // MARK: - PaneLayoutState lenient decoding (saved layouts survive)

    func testPaneLayoutStateDecodesLegacyJSONWithoutThroughlineKey() throws {
        let legacy = """
        {"editMode":"splitView","showOutline":true,"showComments":true,
         "showAIChat":false,"splitEditor":false,"splitEditorSideBySide":false,
         "editorAppearance":"follow","pdfAppearance":"follow"}
        """
        let state = try JSONDecoder().decode(PaneLayoutState.self, from: Data(legacy.utf8))
        XCTAssertTrue(state.showComments)
        XCTAssertFalse(state.showThroughline)
    }

    // MARK: - Package sidecar round-trip (ADR-0016 D2 guard)
    //
    // Uses the internal `makePackageWrapper` / `init(packageWrapper:)` seams
    // because SwiftUI's Read/WriteConfiguration have no public initializers.

    @MainActor
    func testSidecarsRoundTripThroughPackage() throws {
        var doc = ImprintDocument(format: .typst)
        ThroughlineCoordinatorTestHooks.createWithoutMirror(in: &doc)
        XCTAssertTrue(doc.hasThroughline)
        let source = doc.throughlineSource!
        let anchors = doc.throughlineAnchorsJSON!

        let wrapper = try doc.makePackageWrapper()
        let children = wrapper.fileWrappers ?? [:]
        XCTAssertEqual(
            String(data: children["throughline.typ"]!.regularFileContents!, encoding: .utf8),
            source)
        XCTAssertEqual(
            String(data: children["throughline.anchors.json"]!.regularFileContents!, encoding: .utf8),
            anchors)

        // Read back through the package initializer.
        let reread = try ImprintDocument(packageWrapper: wrapper)
        XCTAssertEqual(reread.throughlineSource, source)
        XCTAssertEqual(reread.throughlineAnchorsJSON, anchors)
    }

    func testNonOptedDocumentEmitsNoSidecars() throws {
        let doc = ImprintDocument(format: .typst)
        XCTAssertFalse(doc.hasThroughline)
        let wrapper = try doc.makePackageWrapper()
        let children = wrapper.fileWrappers ?? [:]
        XCTAssertNil(children["throughline.typ"])
        XCTAssertNil(children["throughline.anchors.json"])

        // Opt-in invariant: a second write of the same non-opted document
        // yields the identical file set (no throughline artifacts appear).
        let again = try doc.makePackageWrapper()
        XCTAssertEqual(
            Set((again.fileWrappers ?? [:]).keys), Set(children.keys))
    }
}

/// Test seam: create sidecars without touching the shared store (the store
/// mirror needs the app's group container, unavailable in unit tests).
@MainActor
enum ThroughlineCoordinatorTestHooks {
    static func createWithoutMirror(in document: inout ImprintDocument) {
        let title = document.title.isEmpty ? "Untitled" : document.title
        let source = ThroughlineIdentity.scaffoldSource(title: title)
        let map = ThroughlineIdentity.initialAnchorMap(documentID: document.id, source: source)
        document.throughlineSource = source
        document.throughlineAnchorsJSON = (try? map.serialize()) ?? "{}"
    }
}
