//
//  ImprintRustCore.swift
//  ImprintRustCore
//
//  Re-exports the UniFFI-generated bindings from imprint-core Rust library.
//

import Foundation

// Re-export the FFI module
@_exported import imprint_coreFFI

// The actual Swift bindings will be generated by UniFFI and placed here.
// After running build-xcframework.sh, copy the generated imprint_core.swift
// file to this location or import it in ImprintCore.

/// Placeholder until UniFFI bindings are generated
public struct ImprintRustCoreInfo {
    public static let version = "0.1.0"
    public static let isAvailable = true
}
