//
//  ADSQueryNormalizer.swift
//  PublicationManagerCore
//
//  Pure query normalization for ADS query strings generated by the on-device
//  Foundation Model. Fixes common mistakes (unquoted authors, multi-word values,
//  lowercase operators) without requiring async or actor overhead.
//

import Foundation

// MARK: - ADS Query Normalizer

public enum ADSQueryNormalizer {

    public struct Result {
        public let correctedQuery: String
        public let corrections: [String]
        public var wasModified: Bool { !corrections.isEmpty }
    }

    /// Known text-value fields where multi-word values need quoting.
    private static let textFields: Set<String> = [
        "abs", "title", "object", "full", "body", "aff", "keyword"
    ]

    /// Fields whose values are identifiers — never quote these.
    private static let identifierFields: Set<String> = [
        "year", "bibcode", "doi", "arxiv", "property", "doctype",
        "collection", "bibstem", "orcid", "arxiv_class", "database",
        "identifier", "volume", "issue", "page"
    ]

    /// All known ADS field names (for space-after-colon rule).
    private static let allKnownFields: Set<String> = [
        "author", "first_author", "abs", "abstract", "title",
        "year", "bibcode", "doi", "arxiv", "orcid",
        "aff", "affiliation", "inst", "full", "object", "body",
        "ack", "keyword", "identifier", "citations", "references",
        "property", "doctype", "collection", "bibstem",
        "arxiv_class", "aff_id", "orcid_pub", "orcid_user", "orcid_other",
        "pubdate", "volume", "issue", "page", "bibgroup", "grant", "facility",
        "author_count", "citation_count", "read_count", "vizier", "database"
    ]

    /// Shorthand aliases for common ADS fields.
    /// Single-letter shortcuts for power users in the Cmd+S search overlay.
    private static let fieldShorthands: [(short: String, full: String)] = [
        ("a", "author"),
        ("t", "title"),
        ("b", "bibcode"),
    ]

    // MARK: - Public API

    /// Apply all normalization rules in order.
    public static func normalize(_ query: String) -> Result {
        var current = query
        var corrections: [String] = []

        // Rule 0: Expand field shorthands (a: → author:, t: → title:, b: → bibcode:)
        let (r0, c0) = expandShorthands(current)
        current = r0
        corrections.append(contentsOf: c0)

        // Rule 1: Remove spaces after colons in field qualifiers
        let (r1, c1) = removeSpacesAfterColons(current)
        current = r1
        corrections.append(contentsOf: c1)

        // Rule 2: Quote unquoted author names with commas
        let (r2, c2) = quoteUnquotedAuthors(current)
        current = r2
        corrections.append(contentsOf: c2)

        // Rule 3: Quote unquoted multi-word field values
        let (r3, c3) = quoteMultiWordValues(current)
        current = r3
        corrections.append(contentsOf: c3)

        // Rule 4: Uppercase boolean operators
        let (r4, c4) = uppercaseBooleanOperators(current)
        current = r4
        corrections.append(contentsOf: c4)

        // Rule 5: Fix "First Last" author order
        let (r5, c5) = fixAuthorNameOrder(current)
        current = r5
        corrections.append(contentsOf: c5)

        return Result(correctedQuery: current, corrections: corrections)
    }

    // MARK: - Rule 0: Expand field shorthands

    private static func expandShorthands(_ query: String) -> (String, [String]) {
        var result = query
        var corrections: [String] = []

        for (short, full) in fieldShorthands {
            // Match standalone shorthand at word boundary followed by colon
            // Negative lookbehind for word chars prevents matching inside longer field names
            let pattern = "(?<![\\w])\(NSRegularExpression.escapedPattern(for: short)):(?=\\S)"
            guard let regex = try? NSRegularExpression(pattern: pattern, options: []) else { continue }

            let matches = regex.matches(in: result, range: NSRange(result.startIndex..., in: result))
            for match in matches.reversed() {
                guard let range = Range(match.range, in: result) else { continue }
                result.replaceSubrange(range, with: "\(full):")
                corrections.append("Expanded \(short): → \(full):")
            }
        }

        return (result, corrections)
    }

    // MARK: - Rule 1: Remove spaces after colons

    private static func removeSpacesAfterColons(_ query: String) -> (String, [String]) {
        var result = query
        var corrections: [String] = []

        guard let regex = try? NSRegularExpression(
            pattern: #"(\w+):\s+(?=[^\s])"#,
            options: []
        ) else { return (query, []) }

        let matches = regex.matches(
            in: result,
            range: NSRange(result.startIndex..., in: result)
        )

        // Process matches in reverse to preserve ranges
        for match in matches.reversed() {
            guard let fieldRange = Range(match.range(at: 1), in: result) else { continue }
            let field = String(result[fieldRange])

            guard allKnownFields.contains(field.lowercased()) else { continue }
            guard let fullRange = Range(match.range, in: result) else { continue }

            let replacement = "\(field):"
            result.replaceSubrange(fullRange, with: replacement)
            corrections.append("Removed space after \(field):")
        }

        return (result, corrections)
    }

    // MARK: - Rule 2: Quote unquoted author names with commas

    private static func quoteUnquotedAuthors(_ query: String) -> (String, [String]) {
        var result = query
        var corrections: [String] = []

        // Match author: or first_author: followed by unquoted value containing a comma
        guard let regex = try? NSRegularExpression(
            pattern: #"((?:first_)?author):([^"\s]+,\s*[^"\s]+)"#,
            options: []
        ) else { return (query, []) }

        let matches = regex.matches(
            in: result,
            range: NSRange(result.startIndex..., in: result)
        )

        for match in matches.reversed() {
            guard let fieldRange = Range(match.range(at: 1), in: result),
                  let valueRange = Range(match.range(at: 2), in: result),
                  let fullRange = Range(match.range, in: result) else { continue }

            let field = String(result[fieldRange])
            let value = String(result[valueRange])
            let replacement = "\(field):\"\(value)\""
            result.replaceSubrange(fullRange, with: replacement)
            corrections.append("Quoted author name: \(field):\"\(value)\"")
        }

        return (result, corrections)
    }

    // MARK: - Rule 3: Quote unquoted multi-word field values

    private static func quoteMultiWordValues(_ query: String) -> (String, [String]) {
        // Tokenize the query to find field:value segments where the value
        // spans multiple words but isn't quoted.
        var corrections: [String] = []

        // Parse into tokens, tracking positions
        let tokens = tokenize(query)
        guard !tokens.isEmpty else { return (query, []) }

        var result = ""
        var i = 0

        while i < tokens.count {
            let token = tokens[i]

            // Check for field:value pattern where field is a text field
            if case .fieldValue(let field, let value, let quoted) = token.kind {
                result += token.leadingWhitespace

                if !quoted && textFields.contains(field.lowercased()) {
                    // Scan forward for words that should be part of this value
                    var extraWords: [String] = []
                    var j = i + 1
                    while j < tokens.count {
                        let next = tokens[j]
                        switch next.kind {
                        case .fieldValue:
                            // Hit another field qualifier — stop
                            break
                        case .operator_:
                            // Hit a boolean operator — stop
                            break
                        case .paren:
                            break
                        case .word(let w):
                            // Check if this looks like a boolean operator
                            let upper = w.uppercased()
                            if upper == "AND" || upper == "OR" || upper == "NOT" {
                                break
                            }
                            extraWords.append(w)
                            j += 1
                            continue
                        }
                        break
                    }

                    if !extraWords.isEmpty {
                        let fullValue = ([value] + extraWords).joined(separator: " ")
                        result += "\(field):\"\(fullValue)\""
                        corrections.append("Quoted multi-word value: \(field):\"\(fullValue)\"")
                        i = j
                        continue
                    } else {
                        // Single word, no change needed
                        result += token.text
                    }
                } else {
                    result += token.text
                }
            } else {
                result += token.leadingWhitespace + token.text
            }

            i += 1
        }

        return (result, corrections)
    }

    // MARK: - Rule 4: Uppercase boolean operators

    private static func uppercaseBooleanOperators(_ query: String) -> (String, [String]) {
        var result = query
        var corrections: [String] = []

        // Match standalone and/or/not not inside quotes
        guard let regex = try? NSRegularExpression(
            pattern: #"(?<!["\w])\b(and|or|not)\b(?!["\w])"#,
            options: .caseInsensitive
        ) else { return (query, []) }

        let matches = regex.matches(
            in: result,
            range: NSRange(result.startIndex..., in: result)
        )

        for match in matches.reversed() {
            guard let range = Range(match.range(at: 1), in: result) else { continue }
            let op = String(result[range])

            // Only fix if not already uppercase
            if op != op.uppercased() {
                let upper = op.uppercased()
                result.replaceSubrange(range, with: upper)
                corrections.append("Uppercased operator: \(op) → \(upper)")
            }
        }

        return (result, corrections)
    }

    // MARK: - Rule 5: Fix "First Last" author order

    private static func fixAuthorNameOrder(_ query: String) -> (String, [String]) {
        var result = query
        var corrections: [String] = []

        // Match author:"FirstName LastName" (two capitalized words, no comma)
        guard let regex = try? NSRegularExpression(
            pattern: #"((?:first_)?author):"([A-Z][a-z]+)\s+([A-Z][a-z]+)""#,
            options: []
        ) else { return (query, []) }

        let matches = regex.matches(
            in: result,
            range: NSRange(result.startIndex..., in: result)
        )

        for match in matches.reversed() {
            guard let fieldRange = Range(match.range(at: 1), in: result),
                  let firstRange = Range(match.range(at: 2), in: result),
                  let lastRange = Range(match.range(at: 3), in: result),
                  let fullRange = Range(match.range, in: result) else { continue }

            let field = String(result[fieldRange])
            let firstName = String(result[firstRange])
            let lastName = String(result[lastRange])
            let firstInitial = String(firstName.prefix(1))

            let replacement = "\(field):\"\(lastName), \(firstInitial)\""
            result.replaceSubrange(fullRange, with: replacement)
            corrections.append("Fixed author order: \"\(firstName) \(lastName)\" → \"\(lastName), \(firstInitial)\"")
        }

        return (result, corrections)
    }

    // MARK: - Tokenizer

    private enum TokenKind {
        case fieldValue(field: String, value: String, quoted: Bool)
        case word(String)
        case operator_(String)  // AND, OR, NOT
        case paren(String)      // ( or )
    }

    private struct Token {
        let kind: TokenKind
        let text: String
        let leadingWhitespace: String
    }

    /// Simple tokenizer that splits a query into field:value pairs, words,
    /// operators, and parentheses while respecting quotes.
    private static func tokenize(_ query: String) -> [Token] {
        var tokens: [Token] = []
        var pos = query.startIndex

        while pos < query.endIndex {
            // Consume leading whitespace
            let wsStart = pos
            while pos < query.endIndex && query[pos].isWhitespace {
                pos = query.index(after: pos)
            }
            let ws = String(query[wsStart..<pos])

            guard pos < query.endIndex else { break }

            // Check for functional operators like citations(bibcode:...)
            if let funcMatch = matchFunctionalOperator(query, at: pos) {
                tokens.append(Token(
                    kind: .word(funcMatch.text),
                    text: funcMatch.text,
                    leadingWhitespace: ws
                ))
                pos = funcMatch.end
                continue
            }

            // Check for parentheses
            if query[pos] == "(" || query[pos] == ")" {
                let paren = String(query[pos])
                tokens.append(Token(kind: .paren(paren), text: paren, leadingWhitespace: ws))
                pos = query.index(after: pos)
                continue
            }

            // Try to match field:value
            if let fv = matchFieldValue(query, at: pos) {
                tokens.append(Token(
                    kind: .fieldValue(field: fv.field, value: fv.value, quoted: fv.quoted),
                    text: fv.text,
                    leadingWhitespace: ws
                ))
                pos = fv.end
                continue
            }

            // Match a bare word
            let wordStart = pos
            while pos < query.endIndex && !query[pos].isWhitespace
                    && query[pos] != "(" && query[pos] != ")" {
                pos = query.index(after: pos)
            }
            let word = String(query[wordStart..<pos])

            let upper = word.uppercased()
            if upper == "AND" || upper == "OR" || upper == "NOT" {
                tokens.append(Token(kind: .operator_(word), text: word, leadingWhitespace: ws))
            } else {
                tokens.append(Token(kind: .word(word), text: word, leadingWhitespace: ws))
            }
        }

        return tokens
    }

    private struct FieldValueMatch {
        let field: String
        let value: String
        let quoted: Bool
        let text: String
        let end: String.Index
    }

    private static func matchFieldValue(_ query: String, at start: String.Index) -> FieldValueMatch? {
        // Match field name
        var pos = start
        let fieldStart = pos
        while pos < query.endIndex && (query[pos].isLetter || query[pos] == "_") {
            pos = query.index(after: pos)
        }

        guard pos < query.endIndex && query[pos] == ":" else { return nil }
        let field = String(query[fieldStart..<pos])

        // Skip colon
        pos = query.index(after: pos)
        guard pos < query.endIndex else {
            return FieldValueMatch(field: field, value: "", quoted: false,
                                   text: String(query[start..<pos]), end: pos)
        }

        // Check for quoted value
        if query[pos] == "\"" {
            let quoteStart = query.index(after: pos)
            var quoteEnd = quoteStart
            while quoteEnd < query.endIndex && query[quoteEnd] != "\"" {
                quoteEnd = query.index(after: quoteEnd)
            }
            let value = String(query[quoteStart..<quoteEnd])
            let end = quoteEnd < query.endIndex ? query.index(after: quoteEnd) : quoteEnd
            return FieldValueMatch(field: field, value: value, quoted: true,
                                   text: String(query[start..<end]), end: end)
        }

        // Check for parenthesized value like author:(...)
        if query[pos] == "(" {
            var depth = 1
            var pEnd = query.index(after: pos)
            while pEnd < query.endIndex && depth > 0 {
                if query[pEnd] == "(" { depth += 1 }
                if query[pEnd] == ")" { depth -= 1 }
                pEnd = query.index(after: pEnd)
            }
            let value = String(query[pos..<pEnd])
            return FieldValueMatch(field: field, value: value, quoted: true,
                                   text: String(query[start..<pEnd]), end: pEnd)
        }

        // Unquoted value — read until whitespace or paren
        let valStart = pos
        while pos < query.endIndex && !query[pos].isWhitespace
                && query[pos] != "(" && query[pos] != ")" {
            pos = query.index(after: pos)
        }
        let value = String(query[valStart..<pos])
        return FieldValueMatch(field: field, value: value, quoted: false,
                               text: String(query[start..<pos]), end: pos)
    }

    private struct FuncMatch {
        let text: String
        let end: String.Index
    }

    /// Match functional operators: citations(bibcode:...), references(bibcode:...), similar(bibcode:...)
    private static func matchFunctionalOperator(_ query: String, at start: String.Index) -> FuncMatch? {
        let funcNames = ["citations", "references", "similar", "trending", "reviews"]
        for name in funcNames {
            let remaining = query[start...]
            guard remaining.hasPrefix(name) else { continue }
            let afterName = query.index(start, offsetBy: name.count)
            guard afterName < query.endIndex && query[afterName] == "(" else { continue }

            // Find matching closing paren
            var depth = 1
            var pos = query.index(after: afterName)
            while pos < query.endIndex && depth > 0 {
                if query[pos] == "(" { depth += 1 }
                if query[pos] == ")" { depth -= 1 }
                pos = query.index(after: pos)
            }

            return FuncMatch(text: String(query[start..<pos]), end: pos)
        }
        return nil
    }
}
