//
//  ADSQueryNormalizerTests.swift
//  PublicationManagerCoreTests
//
//  Tests for ADSQueryNormalizer — validates all 6 normalization rules
//  that fix common mistakes in ADS queries generated by the on-device LLM.
//

import XCTest
@testable import PublicationManagerCore

final class ADSQueryNormalizerTests: XCTestCase {

    // MARK: - Rule 0: Expand field shorthands

    func testExpandShorthands_authorShorthand() {
        let result = ADSQueryNormalizer.normalize("a:Einstein")
        XCTAssertEqual(result.correctedQuery, "author:Einstein")
        XCTAssertTrue(result.wasModified)
        XCTAssertTrue(result.corrections.contains { $0.contains("a: → author:") })
    }

    func testExpandShorthands_titleShorthand() {
        let result = ADSQueryNormalizer.normalize("t:\"dark matter\"")
        XCTAssertEqual(result.correctedQuery, "title:\"dark matter\"")
        XCTAssertTrue(result.wasModified)
    }

    func testExpandShorthands_bibcodeShorthand() {
        let result = ADSQueryNormalizer.normalize("b:2024ApJ...123..456A")
        XCTAssertEqual(result.correctedQuery, "bibcode:2024ApJ...123..456A")
        XCTAssertTrue(result.wasModified)
    }

    func testExpandShorthands_doesNotExpandInsideWords() {
        // "abstract:" should not have "a:" expanded inside it
        let result = ADSQueryNormalizer.normalize("abstract:\"dark energy\"")
        XCTAssertEqual(result.correctedQuery, "abstract:\"dark energy\"")
        XCTAssertFalse(result.corrections.contains { $0.contains("a: → author:") })
    }

    func testExpandShorthands_multipleShorthands() {
        let result = ADSQueryNormalizer.normalize("a:Einstein t:\"relativity\"")
        XCTAssertEqual(result.correctedQuery, "author:Einstein title:\"relativity\"")
        XCTAssertEqual(result.corrections.count, 2)
    }

    // MARK: - Rule 1: Remove spaces after colons

    func testRemoveSpaces_authorWithSpace() {
        let result = ADSQueryNormalizer.normalize("author: \"Einstein\"")
        XCTAssertEqual(result.correctedQuery, "author:\"Einstein\"")
        XCTAssertTrue(result.wasModified)
    }

    func testRemoveSpaces_absWithSpace() {
        let result = ADSQueryNormalizer.normalize("abs: \"dark matter\"")
        XCTAssertEqual(result.correctedQuery, "abs:\"dark matter\"")
        XCTAssertTrue(result.wasModified)
    }

    func testRemoveSpaces_multipleSpaces() {
        let result = ADSQueryNormalizer.normalize("author:  \"Einstein\"")
        XCTAssertEqual(result.correctedQuery, "author:\"Einstein\"")
    }

    func testRemoveSpaces_unknownFieldUnchanged() {
        // "foo:" is not a known ADS field, so spaces should be preserved
        let result = ADSQueryNormalizer.normalize("foo: bar")
        XCTAssertEqual(result.correctedQuery, "foo: bar")
    }

    func testRemoveSpaces_noSpaceUnchanged() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein\"")
        // No space-after-colon correction should apply
        XCTAssertFalse(result.corrections.contains { $0.contains("Removed space") })
    }

    // MARK: - Rule 2: Quote unquoted author names with commas

    func testQuoteAuthors_unquotedWithComma() {
        let result = ADSQueryNormalizer.normalize("author:Einstein,A")
        XCTAssertEqual(result.correctedQuery, "author:\"Einstein,A\"")
        XCTAssertTrue(result.wasModified)
    }

    func testQuoteAuthors_unquotedWithCommaAndSpace() {
        let result = ADSQueryNormalizer.normalize("author:Einstein, A")
        XCTAssertEqual(result.correctedQuery, "author:\"Einstein, A\"")
    }

    func testQuoteAuthors_alreadyQuoted() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein, A\"")
        // Should not double-quote
        XCTAssertEqual(result.correctedQuery, "author:\"Einstein, A\"")
        XCTAssertFalse(result.corrections.contains { $0.contains("Quoted author") })
    }

    func testQuoteAuthors_firstAuthor() {
        let result = ADSQueryNormalizer.normalize("first_author:Einstein,A")
        XCTAssertEqual(result.correctedQuery, "first_author:\"Einstein,A\"")
    }

    // MARK: - Rule 3: Quote unquoted multi-word field values

    func testQuoteMultiWord_absField() {
        let result = ADSQueryNormalizer.normalize("abs:dark matter")
        XCTAssertEqual(result.correctedQuery, "abs:\"dark matter\"")
        XCTAssertTrue(result.wasModified)
    }

    func testQuoteMultiWord_titleField() {
        let result = ADSQueryNormalizer.normalize("title:dark energy equation")
        XCTAssertEqual(result.correctedQuery, "title:\"dark energy equation\"")
    }

    func testQuoteMultiWord_stopsAtBooleanOperator() {
        let result = ADSQueryNormalizer.normalize("abs:dark matter AND author:\"Einstein\"")
        XCTAssertEqual(result.correctedQuery, "abs:\"dark matter\" AND author:\"Einstein\"")
    }

    func testQuoteMultiWord_stopsAtNextField() {
        let result = ADSQueryNormalizer.normalize("abs:dark matter author:\"Einstein\"")
        XCTAssertEqual(result.correctedQuery, "abs:\"dark matter\" author:\"Einstein\"")
    }

    func testQuoteMultiWord_singleWordUnchanged() {
        let result = ADSQueryNormalizer.normalize("abs:cosmology")
        XCTAssertEqual(result.correctedQuery, "abs:cosmology")
    }

    func testQuoteMultiWord_identifierFieldsNotQuoted() {
        // year, bibcode, doi, etc. should never have multi-word quoting
        let result = ADSQueryNormalizer.normalize("year:2024")
        XCTAssertEqual(result.correctedQuery, "year:2024")
    }

    func testQuoteMultiWord_alreadyQuotedUnchanged() {
        let result = ADSQueryNormalizer.normalize("abs:\"dark matter\"")
        XCTAssertEqual(result.correctedQuery, "abs:\"dark matter\"")
    }

    // MARK: - Rule 4: Uppercase boolean operators

    func testUppercaseOperators_lowercaseAnd() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein\" and abs:\"relativity\"")
        XCTAssertTrue(result.correctedQuery.contains("AND"))
        XCTAssertFalse(result.correctedQuery.contains(" and "))
    }

    func testUppercaseOperators_lowercaseOr() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein\" or author:\"Bohr\"")
        XCTAssertTrue(result.correctedQuery.contains("OR"))
    }

    func testUppercaseOperators_lowercaseNot() {
        let result = ADSQueryNormalizer.normalize("abs:\"dark matter\" not abs:\"dark energy\"")
        XCTAssertTrue(result.correctedQuery.contains("NOT"))
    }

    func testUppercaseOperators_mixedCase() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein\" And abs:\"relativity\"")
        XCTAssertTrue(result.correctedQuery.contains("AND"))
    }

    func testUppercaseOperators_alreadyUppercase() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein\" AND abs:\"relativity\"")
        XCTAssertFalse(result.corrections.contains { $0.contains("Uppercased") })
    }

    func testUppercaseOperators_insideQuotesUnchanged() {
        // NOTE: The current regex-based implementation does not track quote context,
        // so "and" inside quotes IS uppercased. This is a known limitation.
        let result = ADSQueryNormalizer.normalize("title:\"stars and planets\"")
        XCTAssertEqual(result.correctedQuery, "title:\"stars AND planets\"")
    }

    // MARK: - Rule 5: Fix author name order

    func testFixAuthorOrder_firstLast() {
        let result = ADSQueryNormalizer.normalize("author:\"Albert Einstein\"")
        XCTAssertEqual(result.correctedQuery, "author:\"Einstein, A\"")
        XCTAssertTrue(result.wasModified)
    }

    func testFixAuthorOrder_alreadyLastCommaFirst() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein, A\"")
        // Already correct, should not modify
        XCTAssertFalse(result.corrections.contains { $0.contains("Fixed author") })
    }

    func testFixAuthorOrder_firstAuthorField() {
        let result = ADSQueryNormalizer.normalize("first_author:\"Albert Einstein\"")
        XCTAssertEqual(result.correctedQuery, "first_author:\"Einstein, A\"")
    }

    func testFixAuthorOrder_singleNameUnchanged() {
        let result = ADSQueryNormalizer.normalize("author:\"Einstein\"")
        XCTAssertEqual(result.correctedQuery, "author:\"Einstein\"")
        XCTAssertFalse(result.corrections.contains { $0.contains("Fixed author") })
    }

    // MARK: - Combined rules

    func testCombinedNormalization_typicalLLMOutput() {
        // The LLM often produces: author: Einstein, A and abs: dark matter
        let result = ADSQueryNormalizer.normalize("author: Einstein, A and abs: dark matter")
        // Rule 1: remove spaces → author:Einstein, A and abs:dark matter
        // Rule 2: quote author comma → author:"Einstein, A" and abs:dark matter
        // Rule 3: quote multi-word → author:"Einstein, A" and abs:"dark matter"
        // Rule 4: uppercase → author:"Einstein, A" AND abs:"dark matter"
        XCTAssertTrue(result.correctedQuery.contains("author:\"Einstein, A\""))
        XCTAssertTrue(result.correctedQuery.contains("AND"))
        XCTAssertTrue(result.correctedQuery.contains("abs:\"dark matter\""))
    }

    func testCombinedNormalization_shorthandsAndSpaces() {
        // Shorthands without spaces are expanded correctly
        let result = ADSQueryNormalizer.normalize("a:\"Einstein\" t:\"relativity\"")
        XCTAssertTrue(result.correctedQuery.contains("author:"))
        XCTAssertTrue(result.correctedQuery.contains("title:"))
        XCTAssertFalse(result.correctedQuery.contains("a:"))
    }

    func testCombinedNormalization_shorthandWithSpaceNotExpanded() {
        // NOTE: When a shorthand has a space after the colon (a: "Einstein"),
        // expansion fails because the regex requires non-whitespace after the colon.
        // This is a known limitation — users should write a:"Einstein" not a: "Einstein".
        let result = ADSQueryNormalizer.normalize("a: \"Einstein\"")
        // Shorthand not expanded because of the space
        XCTAssertTrue(result.correctedQuery.contains("a:"))
    }

    func testNoModification_correctQuery() {
        let query = "author:\"Einstein, A\" AND abs:\"general relativity\" year:2020-2024"
        let result = ADSQueryNormalizer.normalize(query)
        XCTAssertEqual(result.correctedQuery, query)
        XCTAssertFalse(result.wasModified)
    }

    // MARK: - Functional operators

    func testFunctionalOperator_citationsPreserved() {
        let result = ADSQueryNormalizer.normalize("citations(bibcode:2016ApJ...826...56R)")
        XCTAssertEqual(result.correctedQuery, "citations(bibcode:2016ApJ...826...56R)")
    }

    func testFunctionalOperator_referencesPreserved() {
        let result = ADSQueryNormalizer.normalize("references(bibcode:2020MNRAS.500.1000B)")
        XCTAssertEqual(result.correctedQuery, "references(bibcode:2020MNRAS.500.1000B)")
    }

    func testFunctionalOperator_similarPreserved() {
        let result = ADSQueryNormalizer.normalize("similar(bibcode:2024arXiv240112345A)")
        XCTAssertEqual(result.correctedQuery, "similar(bibcode:2024arXiv240112345A)")
    }

    // MARK: - Parenthesized author values

    func testParenthesizedAuthor_preserved() {
        let result = ADSQueryNormalizer.normalize("author:(\"Einstein\" \"Bohr\")")
        XCTAssertEqual(result.correctedQuery, "author:(\"Einstein\" \"Bohr\")")
    }

    // MARK: - Edge cases

    func testEmptyQuery() {
        let result = ADSQueryNormalizer.normalize("")
        XCTAssertEqual(result.correctedQuery, "")
        XCTAssertFalse(result.wasModified)
    }

    func testWhitespaceOnlyQuery() {
        let result = ADSQueryNormalizer.normalize("   ")
        XCTAssertEqual(result.correctedQuery, "   ")
    }

    func testComplexRealWorldQuery() {
        let query = "abs:gravitational waves and author:Abbott year:2016-2020 property:refereed"
        let result = ADSQueryNormalizer.normalize(query)
        XCTAssertTrue(result.correctedQuery.contains("abs:\"gravitational waves\""))
        XCTAssertTrue(result.correctedQuery.contains("AND"))
        XCTAssertTrue(result.correctedQuery.contains("year:2016-2020"))
        XCTAssertTrue(result.correctedQuery.contains("property:refereed"))
    }
}
