// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(scix_client_ffiFFI)
import scix_client_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_scix_client_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_scix_client_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * Author info from SciX/ADS API.
 */
public struct ScixAuthor {
    /**
     * Full formatted name (e.g., "Einstein, Albert")
     */
    public var name: String
    /**
     * Family/last name
     */
    public var familyName: String
    /**
     * Given/first name(s)
     */
    public var givenName: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Full formatted name (e.g., "Einstein, Albert")
         */name: String, 
        /**
         * Family/last name
         */familyName: String, 
        /**
         * Given/first name(s)
         */givenName: String?) {
        self.name = name
        self.familyName = familyName
        self.givenName = givenName
    }
}



extension ScixAuthor: Equatable, Hashable {
    public static func ==(lhs: ScixAuthor, rhs: ScixAuthor) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.familyName != rhs.familyName {
            return false
        }
        if lhs.givenName != rhs.givenName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(familyName)
        hasher.combine(givenName)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScixAuthor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScixAuthor {
        return
            try ScixAuthor(
                name: FfiConverterString.read(from: &buf), 
                familyName: FfiConverterString.read(from: &buf), 
                givenName: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ScixAuthor, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.familyName, into: &buf)
        FfiConverterOptionString.write(value.givenName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixAuthor_lift(_ buf: RustBuffer) throws -> ScixAuthor {
    return try FfiConverterTypeScixAuthor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixAuthor_lower(_ value: ScixAuthor) -> RustBuffer {
    return FfiConverterTypeScixAuthor.lower(value)
}


/**
 * SciX/ADS personal library metadata.
 */
public struct ScixLibrary {
    public var id: String
    public var name: String
    public var description: String
    public var numDocuments: Int32
    public var isPublic: Bool
    public var owner: String
    /**
     * User's permission level: "owner" | "admin" | "write" | "read"
     */
    public var permission: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, description: String, numDocuments: Int32, isPublic: Bool, owner: String, 
        /**
         * User's permission level: "owner" | "admin" | "write" | "read"
         */permission: String) {
        self.id = id
        self.name = name
        self.description = description
        self.numDocuments = numDocuments
        self.isPublic = isPublic
        self.owner = owner
        self.permission = permission
    }
}



extension ScixLibrary: Equatable, Hashable {
    public static func ==(lhs: ScixLibrary, rhs: ScixLibrary) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.numDocuments != rhs.numDocuments {
            return false
        }
        if lhs.isPublic != rhs.isPublic {
            return false
        }
        if lhs.owner != rhs.owner {
            return false
        }
        if lhs.permission != rhs.permission {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(description)
        hasher.combine(numDocuments)
        hasher.combine(isPublic)
        hasher.combine(owner)
        hasher.combine(permission)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScixLibrary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScixLibrary {
        return
            try ScixLibrary(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                numDocuments: FfiConverterInt32.read(from: &buf), 
                isPublic: FfiConverterBool.read(from: &buf), 
                owner: FfiConverterString.read(from: &buf), 
                permission: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ScixLibrary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterInt32.write(value.numDocuments, into: &buf)
        FfiConverterBool.write(value.isPublic, into: &buf)
        FfiConverterString.write(value.owner, into: &buf)
        FfiConverterString.write(value.permission, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixLibrary_lift(_ buf: RustBuffer) throws -> ScixLibrary {
    return try FfiConverterTypeScixLibrary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixLibrary_lower(_ value: ScixLibrary) -> RustBuffer {
    return FfiConverterTypeScixLibrary.lower(value)
}


/**
 * SciX/ADS personal library with its bibcodes.
 */
public struct ScixLibraryDetail {
    public var id: String
    public var name: String
    public var description: String
    public var numDocuments: Int32
    public var isPublic: Bool
    public var owner: String
    /**
     * Bibcodes of papers in this library
     */
    public var bibcodes: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, description: String, numDocuments: Int32, isPublic: Bool, owner: String, 
        /**
         * Bibcodes of papers in this library
         */bibcodes: [String]) {
        self.id = id
        self.name = name
        self.description = description
        self.numDocuments = numDocuments
        self.isPublic = isPublic
        self.owner = owner
        self.bibcodes = bibcodes
    }
}



extension ScixLibraryDetail: Equatable, Hashable {
    public static func ==(lhs: ScixLibraryDetail, rhs: ScixLibraryDetail) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.numDocuments != rhs.numDocuments {
            return false
        }
        if lhs.isPublic != rhs.isPublic {
            return false
        }
        if lhs.owner != rhs.owner {
            return false
        }
        if lhs.bibcodes != rhs.bibcodes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(description)
        hasher.combine(numDocuments)
        hasher.combine(isPublic)
        hasher.combine(owner)
        hasher.combine(bibcodes)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScixLibraryDetail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScixLibraryDetail {
        return
            try ScixLibraryDetail(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                numDocuments: FfiConverterInt32.read(from: &buf), 
                isPublic: FfiConverterBool.read(from: &buf), 
                owner: FfiConverterString.read(from: &buf), 
                bibcodes: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ScixLibraryDetail, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterInt32.write(value.numDocuments, into: &buf)
        FfiConverterBool.write(value.isPublic, into: &buf)
        FfiConverterString.write(value.owner, into: &buf)
        FfiConverterSequenceString.write(value.bibcodes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixLibraryDetail_lift(_ buf: RustBuffer) throws -> ScixLibraryDetail {
    return try FfiConverterTypeScixLibraryDetail.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixLibraryDetail_lower(_ value: ScixLibraryDetail) -> RustBuffer {
    return FfiConverterTypeScixLibraryDetail.lower(value)
}


/**
 * A paper from the SciX/ADS API.
 * Used for search results, references, citations, similar papers, and co-reads.
 */
public struct ScixPaper {
    /**
     * ADS bibcode (e.g., "2023ApJ...123..456A")
     */
    public var bibcode: String
    /**
     * Paper title
     */
    public var title: String
    /**
     * Authors
     */
    public var authors: [ScixAuthor]
    /**
     * Publication year
     */
    public var year: Int32?
    /**
     * Journal or publication name
     */
    public var publication: String?
    /**
     * DOI
     */
    public var doi: String?
    /**
     * arXiv identifier (e.g., "2301.12345")
     */
    public var arxivId: String?
    /**
     * Abstract text
     */
    public var abstractText: String?
    /**
     * Citation count
     */
    public var citationCount: Int32?
    /**
     * PDF and web links
     */
    public var pdfLinks: [ScixPdfLink]
    /**
     * ADS/SciX abstract page URL
     */
    public var webUrl: String
    /**
     * Whether paper is open access
     */
    public var isOpenAccess: Bool
    /**
     * Document type (e.g., "article", "inproceedings")
     */
    public var doctype: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * ADS bibcode (e.g., "2023ApJ...123..456A")
         */bibcode: String, 
        /**
         * Paper title
         */title: String, 
        /**
         * Authors
         */authors: [ScixAuthor], 
        /**
         * Publication year
         */year: Int32?, 
        /**
         * Journal or publication name
         */publication: String?, 
        /**
         * DOI
         */doi: String?, 
        /**
         * arXiv identifier (e.g., "2301.12345")
         */arxivId: String?, 
        /**
         * Abstract text
         */abstractText: String?, 
        /**
         * Citation count
         */citationCount: Int32?, 
        /**
         * PDF and web links
         */pdfLinks: [ScixPdfLink], 
        /**
         * ADS/SciX abstract page URL
         */webUrl: String, 
        /**
         * Whether paper is open access
         */isOpenAccess: Bool, 
        /**
         * Document type (e.g., "article", "inproceedings")
         */doctype: String?) {
        self.bibcode = bibcode
        self.title = title
        self.authors = authors
        self.year = year
        self.publication = publication
        self.doi = doi
        self.arxivId = arxivId
        self.abstractText = abstractText
        self.citationCount = citationCount
        self.pdfLinks = pdfLinks
        self.webUrl = webUrl
        self.isOpenAccess = isOpenAccess
        self.doctype = doctype
    }
}



extension ScixPaper: Equatable, Hashable {
    public static func ==(lhs: ScixPaper, rhs: ScixPaper) -> Bool {
        if lhs.bibcode != rhs.bibcode {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.authors != rhs.authors {
            return false
        }
        if lhs.year != rhs.year {
            return false
        }
        if lhs.publication != rhs.publication {
            return false
        }
        if lhs.doi != rhs.doi {
            return false
        }
        if lhs.arxivId != rhs.arxivId {
            return false
        }
        if lhs.abstractText != rhs.abstractText {
            return false
        }
        if lhs.citationCount != rhs.citationCount {
            return false
        }
        if lhs.pdfLinks != rhs.pdfLinks {
            return false
        }
        if lhs.webUrl != rhs.webUrl {
            return false
        }
        if lhs.isOpenAccess != rhs.isOpenAccess {
            return false
        }
        if lhs.doctype != rhs.doctype {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(bibcode)
        hasher.combine(title)
        hasher.combine(authors)
        hasher.combine(year)
        hasher.combine(publication)
        hasher.combine(doi)
        hasher.combine(arxivId)
        hasher.combine(abstractText)
        hasher.combine(citationCount)
        hasher.combine(pdfLinks)
        hasher.combine(webUrl)
        hasher.combine(isOpenAccess)
        hasher.combine(doctype)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScixPaper: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScixPaper {
        return
            try ScixPaper(
                bibcode: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                authors: FfiConverterSequenceTypeScixAuthor.read(from: &buf), 
                year: FfiConverterOptionInt32.read(from: &buf), 
                publication: FfiConverterOptionString.read(from: &buf), 
                doi: FfiConverterOptionString.read(from: &buf), 
                arxivId: FfiConverterOptionString.read(from: &buf), 
                abstractText: FfiConverterOptionString.read(from: &buf), 
                citationCount: FfiConverterOptionInt32.read(from: &buf), 
                pdfLinks: FfiConverterSequenceTypeScixPdfLink.read(from: &buf), 
                webUrl: FfiConverterString.read(from: &buf), 
                isOpenAccess: FfiConverterBool.read(from: &buf), 
                doctype: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ScixPaper, into buf: inout [UInt8]) {
        FfiConverterString.write(value.bibcode, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterSequenceTypeScixAuthor.write(value.authors, into: &buf)
        FfiConverterOptionInt32.write(value.year, into: &buf)
        FfiConverterOptionString.write(value.publication, into: &buf)
        FfiConverterOptionString.write(value.doi, into: &buf)
        FfiConverterOptionString.write(value.arxivId, into: &buf)
        FfiConverterOptionString.write(value.abstractText, into: &buf)
        FfiConverterOptionInt32.write(value.citationCount, into: &buf)
        FfiConverterSequenceTypeScixPdfLink.write(value.pdfLinks, into: &buf)
        FfiConverterString.write(value.webUrl, into: &buf)
        FfiConverterBool.write(value.isOpenAccess, into: &buf)
        FfiConverterOptionString.write(value.doctype, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixPaper_lift(_ buf: RustBuffer) throws -> ScixPaper {
    return try FfiConverterTypeScixPaper.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixPaper_lower(_ value: ScixPaper) -> RustBuffer {
    return FfiConverterTypeScixPaper.lower(value)
}


/**
 * A PDF or web link associated with a paper.
 */
public struct ScixPdfLink {
    /**
     * URL of the PDF or landing page
     */
    public var url: String
    /**
     * Link type: "ArXiv", "Publisher", "AdsScan", "Direct"
     */
    public var linkType: String
    /**
     * Human-readable label
     */
    public var label: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * URL of the PDF or landing page
         */url: String, 
        /**
         * Link type: "ArXiv", "Publisher", "AdsScan", "Direct"
         */linkType: String, 
        /**
         * Human-readable label
         */label: String) {
        self.url = url
        self.linkType = linkType
        self.label = label
    }
}



extension ScixPdfLink: Equatable, Hashable {
    public static func ==(lhs: ScixPdfLink, rhs: ScixPdfLink) -> Bool {
        if lhs.url != rhs.url {
            return false
        }
        if lhs.linkType != rhs.linkType {
            return false
        }
        if lhs.label != rhs.label {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(url)
        hasher.combine(linkType)
        hasher.combine(label)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScixPdfLink: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScixPdfLink {
        return
            try ScixPdfLink(
                url: FfiConverterString.read(from: &buf), 
                linkType: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ScixPdfLink, into buf: inout [UInt8]) {
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.linkType, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixPdfLink_lift(_ buf: RustBuffer) throws -> ScixPdfLink {
    return try FfiConverterTypeScixPdfLink.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixPdfLink_lower(_ value: ScixPdfLink) -> RustBuffer {
    return FfiConverterTypeScixPdfLink.lower(value)
}


/**
 * A collaborator permission entry for a SciX library.
 */
public struct ScixPermission {
    public var email: String
    /**
     * Permission level: "owner" | "admin" | "write" | "read"
     */
    public var permission: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(email: String, 
        /**
         * Permission level: "owner" | "admin" | "write" | "read"
         */permission: String) {
        self.email = email
        self.permission = permission
    }
}



extension ScixPermission: Equatable, Hashable {
    public static func ==(lhs: ScixPermission, rhs: ScixPermission) -> Bool {
        if lhs.email != rhs.email {
            return false
        }
        if lhs.permission != rhs.permission {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(email)
        hasher.combine(permission)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScixPermission: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScixPermission {
        return
            try ScixPermission(
                email: FfiConverterString.read(from: &buf), 
                permission: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ScixPermission, into buf: inout [UInt8]) {
        FfiConverterString.write(value.email, into: &buf)
        FfiConverterString.write(value.permission, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixPermission_lift(_ buf: RustBuffer) throws -> ScixPermission {
    return try FfiConverterTypeScixPermission.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScixPermission_lower(_ value: ScixPermission) -> RustBuffer {
    return FfiConverterTypeScixPermission.lower(value)
}


/**
 * FFI error type for scix-client operations.
 */
public enum ScixFfiError {

    
    
    case ApiError(message: String
    )
    case NetworkError(message: String
    )
    case Unauthorized
    case RateLimited
    case NotFound
    case Internal(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScixFfiError: FfiConverterRustBuffer {
    typealias SwiftType = ScixFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScixFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ApiError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NetworkError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Unauthorized
        case 4: return .RateLimited
        case 5: return .NotFound
        case 6: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ScixFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ApiError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .NetworkError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case .Unauthorized:
            writeInt(&buf, Int32(3))
        
        
        case .RateLimited:
            writeInt(&buf, Int32(4))
        
        
        case .NotFound:
            writeInt(&buf, Int32(5))
        
        
        case let .Internal(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension ScixFfiError: Equatable, Hashable {}

extension ScixFfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt32: FfiConverterRustBuffer {
    typealias SwiftType = Int32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeScixAuthor: FfiConverterRustBuffer {
    typealias SwiftType = [ScixAuthor]

    public static func write(_ value: [ScixAuthor], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeScixAuthor.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ScixAuthor] {
        let len: Int32 = try readInt(&buf)
        var seq = [ScixAuthor]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeScixAuthor.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeScixLibrary: FfiConverterRustBuffer {
    typealias SwiftType = [ScixLibrary]

    public static func write(_ value: [ScixLibrary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeScixLibrary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ScixLibrary] {
        let len: Int32 = try readInt(&buf)
        var seq = [ScixLibrary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeScixLibrary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeScixPaper: FfiConverterRustBuffer {
    typealias SwiftType = [ScixPaper]

    public static func write(_ value: [ScixPaper], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeScixPaper.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ScixPaper] {
        let len: Int32 = try readInt(&buf)
        var seq = [ScixPaper]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeScixPaper.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeScixPdfLink: FfiConverterRustBuffer {
    typealias SwiftType = [ScixPdfLink]

    public static func write(_ value: [ScixPdfLink], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeScixPdfLink.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ScixPdfLink] {
        let len: Int32 = try readInt(&buf)
        var seq = [ScixPdfLink]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeScixPdfLink.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeScixPermission: FfiConverterRustBuffer {
    typealias SwiftType = [ScixPermission]

    public static func write(_ value: [ScixPermission], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeScixPermission.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ScixPermission] {
        let len: Int32 = try readInt(&buf)
        var seq = [ScixPermission]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeScixPermission.read(from: &buf))
        }
        return seq
    }
}
/**
 * Add bibcodes to an existing library.
 */
public func scixAddToLibrary(token: String, libraryId: String, bibcodes: [String])throws  {try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_add_to_library(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),
        FfiConverterSequenceString.lower(bibcodes),$0
    )
}
}
/**
 * Get total result count for a query without fetching paper data.
 *
 * Uses `rows=0` for a lightweight count-only query — no paper data is returned.
 * Useful for query preview features that show how many results a query would return.
 */
public func scixCount(token: String, query: String)throws  -> UInt32 {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_count(
        FfiConverterString.lower(token),
        FfiConverterString.lower(query),$0
    )
})
}
/**
 * Create a new personal library.
 *
 * Returns the ID of the newly created library.
 */
public func scixCreateLibrary(token: String, name: String, description: String, isPublic: Bool, bibcodes: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_create_library(
        FfiConverterString.lower(token),
        FfiConverterString.lower(name),
        FfiConverterString.lower(description),
        FfiConverterBool.lower(isPublic),
        FfiConverterSequenceString.lower(bibcodes),$0
    )
})
}
/**
 * Delete a library.
 */
public func scixDeleteLibrary(token: String, libraryId: String)throws  {try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_delete_library(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),$0
    )
}
}
/**
 * Edit a library's metadata (name, description, public status).
 *
 * Pass `None` for fields that should not be changed.
 */
public func scixEditLibrary(token: String, libraryId: String, name: String?, description: String?, isPublic: Bool?)throws  {try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_edit_library(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),
        FfiConverterOptionString.lower(name),
        FfiConverterOptionString.lower(description),
        FfiConverterOptionBool.lower(isPublic),$0
    )
}
}
/**
 * Export papers as BibTeX.
 *
 * Returns a BibTeX string with entries for all provided bibcodes.
 */
public func scixExportBibtex(token: String, bibcodes: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_export_bibtex(
        FfiConverterString.lower(token),
        FfiConverterSequenceString.lower(bibcodes),$0
    )
})
}
/**
 * Export papers as RIS format.
 */
public func scixExportRis(token: String, bibcodes: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_export_ris(
        FfiConverterString.lower(token),
        FfiConverterSequenceString.lower(bibcodes),$0
    )
})
}
/**
 * Fetch papers that cite the given paper.
 *
 * Uses ADS `citations(bibcode:XXXX)` functional operator.
 */
public func scixFetchCitations(token: String, bibcode: String, maxResults: UInt32)throws  -> [ScixPaper] {
    return try  FfiConverterSequenceTypeScixPaper.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_fetch_citations(
        FfiConverterString.lower(token),
        FfiConverterString.lower(bibcode),
        FfiConverterUInt32.lower(maxResults),$0
    )
})
}
/**
 * Fetch papers frequently co-read with the given paper.
 *
 * Uses ADS `trending(bibcode:XXXX)` functional operator.
 */
public func scixFetchCoreads(token: String, bibcode: String, maxResults: UInt32)throws  -> [ScixPaper] {
    return try  FfiConverterSequenceTypeScixPaper.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_fetch_coreads(
        FfiConverterString.lower(token),
        FfiConverterString.lower(bibcode),
        FfiConverterUInt32.lower(maxResults),$0
    )
})
}
/**
 * Fetch papers that the given paper references (papers it cites).
 *
 * Uses ADS `references(bibcode:XXXX)` functional operator.
 */
public func scixFetchReferences(token: String, bibcode: String, maxResults: UInt32)throws  -> [ScixPaper] {
    return try  FfiConverterSequenceTypeScixPaper.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_fetch_references(
        FfiConverterString.lower(token),
        FfiConverterString.lower(bibcode),
        FfiConverterUInt32.lower(maxResults),$0
    )
})
}
/**
 * Fetch papers with similar content to the given paper.
 *
 * Uses ADS `similar(bibcode:XXXX)` functional operator.
 */
public func scixFetchSimilar(token: String, bibcode: String, maxResults: UInt32)throws  -> [ScixPaper] {
    return try  FfiConverterSequenceTypeScixPaper.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_fetch_similar(
        FfiConverterString.lower(token),
        FfiConverterString.lower(bibcode),
        FfiConverterUInt32.lower(maxResults),$0
    )
})
}
/**
 * Get a library's details including its bibcodes.
 */
public func scixGetLibrary(token: String, libraryId: String)throws  -> ScixLibraryDetail {
    return try  FfiConverterTypeScixLibraryDetail.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_get_library(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),$0
    )
})
}
/**
 * Get collaborator permissions for a library.
 *
 * Returns a list of email/permission pairs for all collaborators.
 */
public func scixGetPermissions(token: String, libraryId: String)throws  -> [ScixPermission] {
    return try  FfiConverterSequenceTypeScixPermission.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_get_permissions(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),$0
    )
})
}
/**
 * List all personal libraries for the authenticated user.
 *
 * Fetches the raw ADS response to capture the `permission` field, which is not
 * exposed by `scix_client::types::Library`.
 */
public func scixListLibraries(token: String)throws  -> [ScixLibrary] {
    return try  FfiConverterSequenceTypeScixLibrary.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_list_libraries(
        FfiConverterString.lower(token),$0
    )
})
}
/**
 * Remove bibcodes from a library.
 */
public func scixRemoveFromLibrary(token: String, libraryId: String, bibcodes: [String])throws  {try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_remove_from_library(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),
        FfiConverterSequenceString.lower(bibcodes),$0
    )
}
}
/**
 * Remove a collaborator from a library by setting their permission to "none".
 */
public func scixRemovePermission(token: String, libraryId: String, email: String)throws  {try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_remove_permission(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),
        FfiConverterString.lower(email),$0
    )
}
}
/**
 * Search NASA ADS / SciX for papers matching a query.
 *
 * Supports full ADS query syntax:
 * - `author:"Einstein, A" year:2020-2024 abs:"gravitational waves"`
 * - `title:dark matter property:refereed`
 * - `citations(bibcode:2016PhRvL.116f1102A)`
 */
public func scixSearch(token: String, query: String, maxResults: UInt32)throws  -> [ScixPaper] {
    return try  FfiConverterSequenceTypeScixPaper.lift(try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_search(
        FfiConverterString.lower(token),
        FfiConverterString.lower(query),
        FfiConverterUInt32.lower(maxResults),$0
    )
})
}
/**
 * Transfer ownership of a library to another user.
 */
public func scixTransferLibrary(token: String, libraryId: String, email: String)throws  {try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_transfer_library(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),
        FfiConverterString.lower(email),$0
    )
}
}
/**
 * Set (or update) a collaborator's permission level on a library.
 *
 * `permission` must be one of: "owner", "admin", "write", "read".
 */
public func scixUpdatePermission(token: String, libraryId: String, email: String, permission: String)throws  {try rustCallWithError(FfiConverterTypeScixFfiError.lift) {
    uniffi_scix_client_ffi_fn_func_scix_update_permission(
        FfiConverterString.lower(token),
        FfiConverterString.lower(libraryId),
        FfiConverterString.lower(email),
        FfiConverterString.lower(permission),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_scix_client_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_add_to_library() != 13637) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_count() != 37775) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_create_library() != 34065) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_delete_library() != 62864) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_edit_library() != 40928) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_export_bibtex() != 7431) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_export_ris() != 47442) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_fetch_citations() != 37093) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_fetch_coreads() != 9470) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_fetch_references() != 51223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_fetch_similar() != 13925) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_get_library() != 43236) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_get_permissions() != 57959) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_list_libraries() != 3849) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_remove_from_library() != 17112) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_remove_permission() != 4539) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_search() != 31722) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_transfer_library() != 61823) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_scix_client_ffi_checksum_func_scix_update_permission() != 18826) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all