//! Title-quality filtering and best-field resolution for PDF metadata.
//!
//! Port of the pure-logic half of
//! `PublicationManagerCore/DragDrop/PDFMetadataExtractor.swift`:
//! `PDFExtractedMetadata.isPlausibleTitle`, `bestTitle`, `bestAuthors`,
//! `bestYear`, `hasIdentifier`, and — as a **retired reference only** —
//! `extractTitleFromFirstPage`.
//!
//! Everything here is string logic over values PDFKit already handed us, so
//! none of it has a reason to be Swift. The PDFKit/pdfium calls that *produce*
//! those values stay on the platform side.
//!
//! Pinned by `tests/stage7_pdf_parity.rs` against
//! `test_fixtures/golden/pdf_plausible_title.json`,
//! `pdf_best_metadata.json` and `pdf_first_page_title.json`.

use impress_smart_search::foundation::{trim_ws, trim_ws_nl};
use lazy_static::lazy_static;
use regex::Regex;
use unicode_segmentation::UnicodeSegmentation;

/// Swift `String.count` counts extended grapheme clusters, not scalars.
///
/// Every length test ported here came from Swift `count`, so it is measured the
/// same way. `str::len()` (bytes) would reject `"Ångström"`-class titles at a
/// 6-char floor for the wrong reason, and `chars().count()` would accept a
/// 3-cluster decomposed string as 6.
fn swift_count(s: &str) -> usize {
    s.graphemes(true).count()
}

lazy_static! {
    /// Bare publisher PII shape: `NNNN-NNNN(YY)NNNNNN-N`, or just `NNNN-NNNNNN`.
    ///
    /// Swift applied this with `range(of:options:.regularExpression)`, which is
    /// a *search*, not a full match — but the pattern is anchored `^…$` at both
    /// ends, so the search can only succeed on a whole-string match. Rust's
    /// `is_match` is therefore exactly equivalent, and the corpus proves it:
    /// `pdf_plausible_title.json` contains both the bare PII codes (rejected)
    /// and `"10.1038/nature12373 and more"` (accepted precisely because the
    /// anchors defeat the search).
    ///
    /// One theoretical gap: ICU's `$` also matches before a single trailing
    /// newline, Rust's does not. Unreachable here — `isPlausibleTitle` trims
    /// `.whitespacesAndNewlines` off both ends before either regex runs.
    static ref PII_SHAPE: Regex =
        Regex::new(r"^\d{4}-\d{4,6}(\([0-9A-Z]{1,6}\))?[-0-9A-Z]*$").unwrap();

    /// A `titleAttribute` that is nothing but a DOI. Same anchoring argument.
    static ref BARE_DOI: Regex = Regex::new(r"^10\.\d{3,}/[^\s]+$").unwrap();
}

/// Autogenerated titles from tooling defaults, matched exactly (lowercased).
const JUNK_EXACT: &[&str] = &[
    "document1",
    "document",
    "manuscript",
    "paper",
    "article",
    "preprint",
    "draft",
    "untitled 1",
    "untitled document",
];

/// Junk prefixes, matched against the lowercased trimmed candidate.
const JUNK_PREFIXES: &[&str] = &["pii:", "doi:", "microsoft word -", "untitled"];

/// The skip list of the retired `extractTitleFromFirstPage`, verbatim.
///
/// Kept separate from — and deliberately NOT reconciled with —
/// `metadata_heuristics::SKIP_PATTERNS`, which has eight more entries
/// (`received`, `vol.`, `no.`, `©`, `introduction`, `keywords:`, `pacs:`,
/// `msc:`). The gap is the point: see [`swift_first_page_title`].
const SWIFT_FIRST_PAGE_SKIP_PATTERNS: &[&str] = &[
    "preprint",
    "submitted",
    "accepted",
    "published",
    "journal",
    "volume",
    "issue",
    "pages",
    "doi:",
    "arxiv:",
    "http",
    "www",
    "copyright",
    "all rights reserved",
    "abstract",
];

/// Whether a PDF `titleAttribute` is worth trusting as a title.
///
/// Publisher PDFs routinely ship garbage here — PII codes
/// (`"PII: 0360-1285(85)90002-4"`), LaTeX/Word export artifacts
/// (`"Microsoft Word - manuscript.docx"`), or the literal `"Untitled"`. When
/// this returns `false` the caller falls through to the heuristic title.
///
/// Rejects: fewer than 6 visible characters, `"untitled"`, the junk prefixes,
/// the tooling-default exact set, bare PII codes, bare DOIs, and anything with
/// no letter in it at all.
pub fn is_plausible_title(candidate: &str) -> bool {
    let trimmed = trim_ws_nl(candidate);
    if swift_count(trimmed) < 6 {
        return false;
    }
    let lower = trimmed.to_lowercase();

    // Subsumed by the `"untitled"` entry in JUNK_PREFIXES below. Preserved so
    // this port stays line-for-line auditable against the Swift original —
    // deleting it would be the first silent edit in a chain of them.
    if lower == "untitled" {
        return false;
    }

    if JUNK_PREFIXES.iter().any(|p| lower.starts_with(p)) {
        return false;
    }

    if JUNK_EXACT.contains(&lower.as_str()) {
        return false;
    }

    if PII_SHAPE.is_match(trimmed) {
        return false;
    }

    if BARE_DOI.is_match(trimmed) {
        return false;
    }

    // Swift used `rangeOfCharacter(from: .letters)`, i.e. Unicode general
    // category L* — NOT ASCII. `char::is_alphabetic` is the equivalent, and it
    // is why `"Ångström Measurements of Müller Bands"` survives while
    // `"1234567890"` and `"!!!???"` do not.
    trimmed.chars().any(char::is_alphabetic)
}

/// The fields `PDFExtractedMetadata` resolves `best*` from.
///
/// Field names deliberately mirror the Swift properties so the golden corpus,
/// the Swift struct and this port read as one thing. Only the fields the pure
/// logic actually consults are present; `subject`, `keywords`, `confidence` and
/// the dates are carried by the Swift struct and never read here.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PdfExtractedFields {
    /// `titleAttribute` from the PDF document properties. Not trusted blindly.
    pub title: Option<String>,
    /// `authorAttribute` from the PDF document properties.
    pub author: Option<String>,
    /// Title recovered from page-1 text by `metadata_heuristics::extract_title`.
    pub heuristic_title: Option<String>,
    /// Authors recovered from page-1 text.
    pub heuristic_authors: Vec<String>,
    /// Year recovered from page-1 text.
    pub heuristic_year: Option<i32>,
    /// Last-resort title fragment lifted off page 1.
    pub first_page_text: Option<String>,
    /// DOI scanned out of the page text.
    pub extracted_doi: Option<String>,
    /// arXiv id scanned out of the page text.
    pub extracted_arxiv_id: Option<String>,
    /// ADS bibcode scanned out of the page text.
    pub extracted_bibcode: Option<String>,
}

impl PdfExtractedFields {
    /// Whether any identifier was extracted.
    pub fn has_identifier(&self) -> bool {
        self.extracted_doi.is_some()
            || self.extracted_arxiv_id.is_some()
            || self.extracted_bibcode.is_some()
    }

    /// Best title: document properties → heuristic → first-page fragment.
    ///
    /// Note the asymmetry, which is preserved: the *document* title must pass
    /// [`is_plausible_title`], but the *heuristic* title only has to be
    /// non-empty. So a two-character heuristic title wins over a good
    /// first-page fragment (corpus case `heuristic-junk-then-firstpage`, where
    /// `bestTitle == "ab"`). It is not a divergence-worthy bug: the heuristic
    /// extractor is the one component that already filtered its own input, and
    /// tightening the gate here would change which title real imports get
    /// without a corpus to say the new one is better.
    pub fn best_title(&self) -> Option<String> {
        if let Some(title) = &self.title {
            if is_plausible_title(title) {
                return Some(title.clone());
            }
        }
        if let Some(heuristic) = &self.heuristic_title {
            if !heuristic.is_empty() {
                return Some(heuristic.clone());
            }
        }
        self.first_page_text.clone()
    }

    /// Best authors: document properties → heuristic.
    ///
    /// Diverges from Swift on one point: the gate is "the document author has
    /// *visible* content", not "the string is non-empty". See
    /// [`Self::best_authors_swift`] for the original and
    /// `stage7_pdf_parity.rs` for the reason.
    pub fn best_authors(&self) -> Vec<String> {
        match &self.author {
            Some(author) if !trim_ws_nl(author).is_empty() => split_document_author(author),
            _ => self.heuristic_authors.clone(),
        }
    }

    /// `bestAuthors` exactly as Swift computed it, kept as the parity witness.
    ///
    /// The gate is `!author.isEmpty` on the *untrimmed* string, so a
    /// `titleAttribute` of `"   "` counts as "the document told us the authors"
    /// — and then the comma split plus the non-empty filter throws every
    /// component away, yielding `[]`. The heuristically recovered authors are
    /// discarded on the way past.
    pub fn best_authors_swift(&self) -> Vec<String> {
        match &self.author {
            Some(author) if !author.is_empty() => split_document_author(author),
            _ => self.heuristic_authors.clone(),
        }
    }

    /// Best year: heuristic only — PDF document properties carry no year field.
    pub fn best_year(&self) -> Option<i32> {
        self.heuristic_year
    }
}

/// Swift `author.components(separatedBy: ",").map(trim .whitespaces).filter(non-empty)`.
///
/// Splits on commas ONLY. A `titleAttribute` of `"Smith, John; Doe, Jane"`
/// therefore yields `["Smith", "John; Doe", "Jane"]` — three mangled names
/// instead of two real ones (corpus case `authors-from-doc-author`). Preserved,
/// and preserved deliberately: the comma-separated case is mangled the same way
/// (`"Smith, John, Doe, Jane"` → four fragments), so the fix is not "also split
/// on `;`" but "parse names", which imbib already does properly in
/// `impress-bibtex`'s author parser. Routing this through it is a behaviour
/// change to every PDF import and needs its own corpus, not a one-line patch
/// smuggled into a parity port.
fn split_document_author(author: &str) -> Vec<String> {
    author
        .split(',')
        .map(|part| trim_ws(part).to_string())
        .filter(|part| !part.is_empty())
        .collect()
}

// ── The retired duplicate ───────────────────────────────────────────────────

/// Foundation `CharacterSet.newlines`: U+000A–U+000D, U+0085, U+2028, U+2029.
///
/// `str::lines()` is not a substitute — it treats `\r\n` as one break, ignores a
/// lone `\r`, and ignores U+2028/U+2029 entirely. PDF text extraction emits all
/// of these.
fn is_newline(c: char) -> bool {
    matches!(
        c,
        '\n' | '\u{000B}' | '\u{000C}' | '\r' | '\u{0085}' | '\u{2028}' | '\u{2029}'
    )
}

/// **Retired.** Swift-parity reference port of
/// `PDFMetadataExtractor.extractTitleFromFirstPage`.
///
/// This is the drifted duplicate of
/// [`crate::pdf::metadata_heuristics`]'s `extract_title`, and it is strictly
/// worse than it in five ways: it scans 20 lines instead of 25, keeps 2
/// candidates instead of 3, has a shorter skip-pattern list (no `received`,
/// `vol.`, `no.`, `©`, `introduction`, `keywords:`, `pacs:`, `msc:`), never
/// checks for `department`/`laboratory` affiliations, does not stop once it has
/// passed an author line, and does not run `clean_title`. The visible
/// consequence, pinned in `stage7_pdf_parity.rs`, is that on a normal paper it
/// glues the author line onto the end of the title.
///
/// It exists ONLY so the parity suite can prove the port reproduces the Swift
/// behaviour and then demonstrate, on the same eight inputs, what the surviving
/// implementation does instead. Production code must call
/// `extract_metadata_heuristics_internal` — do not wire this up.
pub fn swift_first_page_title(text: &str) -> Option<String> {
    let lines: Vec<&str> = text
        .split(is_newline)
        .map(trim_ws)
        .filter(|l| !l.is_empty())
        .collect();

    let mut candidate_lines: Vec<&str> = Vec::new();

    for line in lines.iter().take(20) {
        let lowercased = line.to_lowercase();

        if SWIFT_FIRST_PAGE_SKIP_PATTERNS
            .iter()
            .any(|p| lowercased.contains(p))
        {
            continue;
        }

        if swift_count(line) < 10 {
            continue;
        }

        // Swift: `lowercased.contains(" and ") && line.filter { $0.isUppercase }.count > 3`.
        // Counted over scalars rather than grapheme clusters; the two differ
        // only for a decomposed uppercase letter, which cannot change a `> 3`
        // verdict without also changing it in Swift.
        if lowercased.contains(" and ") && line.chars().filter(|c| c.is_uppercase()).count() > 3 {
            continue;
        }

        if lowercased.contains('@')
            || lowercased.contains("university")
            || lowercased.contains("institute")
        {
            continue;
        }

        candidate_lines.push(line);

        if candidate_lines.len() >= 2 {
            break;
        }
    }

    if candidate_lines.len() >= 2 {
        let combined = candidate_lines.join(" ");
        if swift_count(&combined) <= 300 {
            return Some(combined);
        }
    }

    candidate_lines.first().map(|l| (*l).to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn six_visible_character_floor_ignores_surrounding_whitespace() {
        assert!(!is_plausible_title("  ab  "));
        assert!(is_plausible_title("  abcdef  "));
    }

    #[test]
    fn zero_width_space_is_trimmed_like_foundation_does() {
        // Rust's `str::trim()` leaves U+200B in place, so a naive port would
        // measure 6 clusters here and disagree with Swift on the floor.
        assert_eq!(trim_ws_nl("\u{200B}abcde\u{200B}"), "abcde");
        assert!(!is_plausible_title("\u{200B}abcde\u{200B}"));
    }

    #[test]
    fn anchored_patterns_do_not_fire_mid_string() {
        assert!(is_plausible_title("Erratum 1234-5678(96)00123-4"));
        assert!(is_plausible_title("A title with 10.1038/x inside it"));
    }

    #[test]
    fn has_identifier_is_an_or_over_all_three() {
        let mut fields = PdfExtractedFields::default();
        assert!(!fields.has_identifier());
        fields.extracted_bibcode = Some("2023ApJ...123..456A".into());
        assert!(fields.has_identifier());
    }
}
