#!/usr/bin/env bash
# Delete the DerivedData that belongs to projects which no longer exist.
#
# WHY THIS DIRECTORY GROWS WITHOUT BOUND. Xcode names each build directory
# after a hash of the .xcodeproj's ABSOLUTE PATH, and never removes one. Two
# habits of this repo make that unbounded rather than merely untidy:
#
#   * every agent session gets a throwaway git worktree under
#     `.claude/worktrees/<name>/`, so the same app hashes differently in each
#     one — and when the worktree is deleted, its multi-gigabyte build cache
#     is not;
#   * `.xcodeproj` is gitignored and regenerated by xcodegen, so it exists at
#     as many paths as there are checkouts.
#
# On 2026-09-09 that had reached 137 GB, of which 36 GB belonged to twelve
# worktrees that had not existed for weeks.
#
# THE RULE. Every Xcode-made directory records its origin in `info.plist` as
# `WorkspacePath`. If that path is gone, the cache cannot be reused by
# anything, ever — deleting it is provably free. That is the default, and it
# is why this is safe to run unattended: it never has to guess.
#
# `--stale-days N` additionally removes caches whose project DOES still exist
# but which nothing has touched in N days. That one is a judgement call (the
# next build of that project becomes a full rebuild), so it is opt-in.
#
# `--products` empties `Build/Products` in every directory EXCEPT the six the
# build script owns. Those products are duplicate .app bundles that Spotlight
# indexes and can rank above ~/Applications: on 2026-09-08 an Xcode GUI build
# left an imbib.app four hours newer than the install. Intermediates are kept,
# so the next GUI build relinks rather than recompiling. This is remediation,
# not prevention — Xcode recreates them on the next build, and only the
# Spotlight Privacy exclusion stops them mattering. See
# docs/build-machine-hygiene.md.
#
# Usage:
#   scripts/prune-derived-data.sh                  # dry run, dead caches only
#   scripts/prune-derived-data.sh --apply          # delete them
#   scripts/prune-derived-data.sh --apply --stale-days 30
#   scripts/prune-derived-data.sh --apply --products
#   scripts/prune-derived-data.sh --apply --quiet  # for build scripts

set -uo pipefail

ROOT="${DERIVED_DATA_ROOT:-$HOME/Library/Developer/Xcode/DerivedData}"
APPLY=no
QUIET=no
STALE_DAYS=0
PRODUCTS=no

while [ $# -gt 0 ]; do
    case "$1" in
        --apply) APPLY=yes ;;
        --quiet) QUIET=yes ;;
        --stale-days) STALE_DAYS="${2:?--stale-days needs a number}"; shift ;;
        --products) PRODUCTS=yes ;;
        -h|--help) sed -n '2,32p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

say() { [ "$QUIET" = yes ] || printf '%s\n' "$*"; }

[ -d "$ROOT" ] || { say "no DerivedData at $ROOT"; exit 0; }

# The six directories `build-impress-app.sh` builds into are load-bearing:
# they are what gets installed to ~/Applications, so they are never stale and
# never pruned, whatever their mtime says.
is_protected() {
    case "$1" in
        imbib|imprint|implore|impel|impart|impress) return 0 ;;
        *.noindex) return 0 ;;   # ModuleCache & friends — Xcode's, not ours
        *) return 1 ;;
    esac
}

now=$(date +%s)
freed=0
count=0

for path in "$ROOT"/*/; do
    dir="$(basename "$path")"
    [ "$dir" = "*" ] && break
    is_protected "$dir" && continue

    reason=""
    ws="$(plutil -extract WorkspacePath raw "$path/info.plist" 2>/dev/null || true)"

    if [ -z "$ws" ]; then
        # No origin recorded at all (Xcode's "Unsaved Document" scratch dirs,
        # and anything a tool created by hand). Nothing can claim it.
        reason="no project recorded"
    elif [ ! -e "$ws" ]; then
        reason="project gone: $(printf '%s' "$ws" | sed "s|^$HOME|~|")"
    elif [ "$STALE_DAYS" -gt 0 ]; then
        mtime=$(stat -f '%m' "$path" 2>/dev/null || echo "$now")
        age_days=$(( (now - mtime) / 86400 ))
        if [ "$age_days" -ge "$STALE_DAYS" ]; then
            reason="untouched for ${age_days}d"
        fi
    fi

    [ -z "$reason" ] && continue

    mb=$(du -sm "$path" 2>/dev/null | cut -f1)
    mb=${mb:-0}
    freed=$(( freed + mb ))
    count=$(( count + 1 ))

    if [ "$APPLY" = yes ]; then
        say "  removed  ${mb}MB  $dir — $reason"
        rm -rf "$path"
    else
        say "  would remove  ${mb}MB  $dir — $reason"
    fi
done

if [ "$PRODUCTS" = yes ]; then
    for path in "$ROOT"/*/; do
        dir="$(basename "$path")"
        [ "$dir" = "*" ] && break
        # The six the build script owns are exempt at ALL times: the
        # ~/MyApplications/<app>.app aliases are symlinks straight into their
        # Build/Products, so emptying one dangles the alias the user launches.
        is_protected "$dir" && continue
        [ -d "$path/Build/Products" ] || continue

        mb=$(du -sm "$path/Build/Products" 2>/dev/null | cut -f1)
        mb=${mb:-0}
        freed=$(( freed + mb ))
        count=$(( count + 1 ))
        if [ "$APPLY" = yes ]; then
            say "  emptied  ${mb}MB  $dir/Build/Products — duplicate app bundles"
            rm -rf "$path/Build/Products"
        else
            say "  would empty  ${mb}MB  $dir/Build/Products — duplicate app bundles"
        fi
    done
fi

# A second, quieter leak: DerivedData directories INSIDE a checkout. .gitignore
# calls these "non-standard in-tree DerivedData (use Xcode's global DerivedData
# instead)", so they are unwanted wherever they appear — but they are only ever
# created by a GUI session that changed its build location, and they can belong
# to a checkout this script has no business touching. Report, never delete.
repo_root="$(cd "$(dirname "$0")/.." 2>/dev/null && pwd || true)"
if [ -n "$repo_root" ]; then
    while IFS= read -r intree; do
        [ -n "$intree" ] || continue
        say "  NOTE  $(du -sm "$intree" 2>/dev/null | cut -f1)MB in-tree DerivedData: $(printf '%s' "$intree" | sed "s|^$HOME|~|")"
        say "        .gitignore says use the global DerivedData; delete it when you know whose it is."
    done < <(find "$repo_root" -maxdepth 4 -type d -name DerivedData 2>/dev/null)
fi

if [ "$count" -eq 0 ]; then
    say "DerivedData is clean — nothing to prune."
elif [ "$APPLY" = yes ]; then
    say "Pruned $count director$([ "$count" = 1 ] && echo y || echo ies), $(( freed / 1024 )) GB (${freed} MB)."
else
    say "$count director$([ "$count" = 1 ] && echo y || echo ies), $(( freed / 1024 )) GB (${freed} MB) — re-run with --apply to delete."
fi
