use crate::reference::EdgeType;
use crate::registry::SchemaRegistry;
use crate::schema::{FieldDef, FieldType, Schema};

/// Schema for visualizations and figures produced by implore.
pub fn figure_schema() -> Schema {
    Schema {
        id: "figure".into(),
        name: "Figure".into(),
        version: "1.0.0".into(),
        fields: vec![
            field("format", FieldType::String, true),
            optional_string("title"),
            optional_string("caption"),
            optional_string("data_hash"),
            optional_string("script_hash"),
            field("width", FieldType::Int, false),
            field("height", FieldType::Int, false),
            optional_string("script_language"),
        ],
        expected_edges: vec![EdgeType::Visualizes, EdgeType::Attaches],
        inherits: None,
    }
}

/// Schema for datasets loaded or generated by implore.
pub fn dataset_schema() -> Schema {
    Schema {
        id: "dataset".into(),
        name: "Dataset".into(),
        version: "1.0.0".into(),
        fields: vec![
            field("name", FieldType::String, true),
            field("format", FieldType::String, true),
            field("row_count", FieldType::Int, false),
            field("column_count", FieldType::Int, false),
            optional_string("data_hash"),
            optional_string("description"),
            optional_string("source_url"),
        ],
        expected_edges: vec![EdgeType::Attaches],
        inherits: None,
    }
}

/// Register figure and dataset schemas for implore.
pub fn register_implore_schemas(registry: &mut SchemaRegistry) {
    registry
        .register(figure_schema())
        .expect("implore/figure schema registration");
    registry
        .register(dataset_schema())
        .expect("implore/dataset schema registration");
}

fn field(name: &str, field_type: FieldType, required: bool) -> FieldDef {
    FieldDef {
        name: name.into(),
        field_type,
        required,
        description: None,
    }
}

fn optional_string(name: &str) -> FieldDef {
    FieldDef {
        name: name.into(),
        field_type: FieldType::String,
        required: false,
        description: None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_implore_schemas_succeeds() {
        let mut reg = SchemaRegistry::new();
        register_implore_schemas(&mut reg);

        assert!(reg.get("figure").is_some());
        assert!(reg.get("dataset").is_some());
    }

    #[test]
    fn figure_schema_has_required_format() {
        let schema = figure_schema();
        let has_required_format = schema
            .fields
            .iter()
            .any(|f| f.name == "format" && f.required);
        assert!(has_required_format, "figure schema must have required 'format' field");
    }

    #[test]
    fn dataset_schema_has_required_fields() {
        let schema = dataset_schema();
        let has_name = schema.fields.iter().any(|f| f.name == "name" && f.required);
        let has_format = schema.fields.iter().any(|f| f.name == "format" && f.required);
        assert!(has_name, "dataset schema must have required 'name' field");
        assert!(has_format, "dataset schema must have required 'format' field");
    }

    #[test]
    fn figure_has_visualizes_edge() {
        let schema = figure_schema();
        assert!(
            schema.expected_edges.contains(&EdgeType::Visualizes),
            "figure schema must include Visualizes edge"
        );
    }

    #[test]
    fn dataset_has_attaches_edge() {
        let schema = dataset_schema();
        assert!(
            schema.expected_edges.contains(&EdgeType::Attaches),
            "dataset schema must include Attaches edge"
        );
    }
}
