//
//  BibliographyProjector.swift
//  imprint
//
//  Live .bib file projection: when the manuscript's cite keys change,
//  regenerate the sidecar .bib file from imbib's shared store.
//
//  Reads BibTeX source of truth via ImprintPublicationService (direct SQL,
//  no HTTP). Preserves entries that aren't in imbib (manual additions).
//
//  When a cite key is missing from the local store but the document has a
//  cached BibTeX stub for it with a DOI / arXiv id / bibcode, the projector
//  asks imbib to fetch the paper via `CitationResolver` — so adding a new
//  citation by DOI lands in the `.bib` automatically on the next debounce.
//

import Foundation
import ImbibRustCore
import ImpressKit
import ImpressLogging

/// Projects the current manuscript's cite keys into a sidecar .bib file.
///
/// The projector is an actor — all filesystem writes are serialized even
/// when multiple debounced updates fire. Each new `scheduleUpdate` cancels
/// any in-flight debounce and restarts the 500ms timer.
public actor BibliographyProjector {

    public static let shared = BibliographyProjector()

    private var pendingTask: Task<Void, Never>?
    private let debounceMs: UInt64 = 500

    /// Cite keys the projector has already tried to resolve via HTTP and
    /// failed. Prevents re-attempting the same unresolvable key on every
    /// debounce pass. Cleared when imbib's library changes.
    private var unresolvableKeys: Set<String> = []

    /// Cite keys currently being resolved — prevents duplicate concurrent
    /// resolves for the same key across debounce passes.
    private var inFlightKeys: Set<String> = []

    private init() {
        Task { [weak self] in
            await self?.observeLibraryChanges()
        }
    }

    // MARK: - Public API

    /// Schedule a .bib file regeneration. Cancels any pending update.
    ///
    /// - Parameters:
    ///   - source: The full manuscript source (used to extract cite keys)
    ///   - bibFileURL: Destination .bib file path (sidecar next to .tex)
    ///   - bibliography: Cached BibTeX entries from the manuscript (cite key →
    ///     entry text). Used to extract identifiers for missing keys.
    public func scheduleUpdate(
        source: String,
        bibFileURL: URL,
        bibliography: [String: String] = [:]
    ) {
        pendingTask?.cancel()
        pendingTask = Task { [weak self] in
            guard let self else { return }
            try? await Task.sleep(for: .milliseconds(Int(debounceMs)))
            if Task.isCancelled { return }
            await self.performUpdate(source: source, bibFileURL: bibFileURL, bibliography: bibliography)
        }
    }

    // MARK: - Private

    private func performUpdate(
        source: String,
        bibFileURL: URL,
        bibliography: [String: String]
    ) async {
        // Extract cite keys from the manuscript
        let citeKeys = await Self.extractCiteKeys(from: source)
        guard !citeKeys.isEmpty else {
            logInfo("BibliographyProjector: no cite keys, skipping", category: "bib-projector")
            return
        }

        // Resolve each cite key to a BibTeX entry via the shared store
        var entries: [(key: String, bibtex: String)] = []
        var missing: [String] = []

        for key in citeKeys {
            let row = await MainActor.run {
                ImprintPublicationService.shared.findByCiteKey(key)
            }
            guard let row else {
                missing.append(key)
                continue
            }
            let detail = await MainActor.run {
                ImprintPublicationService.shared.detail(id: row.id)
            }
            guard let bibtex = detail?.rawBibtex, !bibtex.isEmpty else {
                let synth = synthesizeBibTeX(for: row)
                entries.append((key, synth))
                continue
            }
            entries.append((key, bibtex))
        }

        // Read any existing entries from the .bib file and merge.
        let existingEntries = readExistingEntries(at: bibFileURL)
        let knownKeys = Set(entries.map(\.key))
        let preserved = existingEntries.filter { !knownKeys.contains($0.key) }

        // Build final content
        var content = "% Generated by imprint BibliographyProjector — \(ISO8601DateFormatter().string(from: Date()))\n"
        content += "% Cite keys extracted from manuscript: \(citeKeys.count) entries\n"
        if !missing.isEmpty {
            content += "% Missing from imbib: \(missing.joined(separator: ", "))\n"
        }
        content += "\n"

        for (key, bibtex) in entries.sorted(by: { $0.key < $1.key }) {
            content += "% \(key)\n"
            content += bibtex.trimmingCharacters(in: .whitespacesAndNewlines)
            content += "\n\n"
        }

        if !preserved.isEmpty {
            content += "% === Preserved entries (not in imbib) ===\n\n"
            for (key, bibtex) in preserved.sorted(by: { $0.key < $1.key }) {
                content += "% \(key)\n"
                content += bibtex
                content += "\n\n"
            }
        }

        // Ensure parent directory exists (temp compile dir may not yet be created)
        let parentDir = bibFileURL.deletingLastPathComponent()
        try? FileManager.default.createDirectory(at: parentDir, withIntermediateDirectories: true)

        do {
            try content.write(to: bibFileURL, atomically: true, encoding: .utf8)
            logInfo("BibliographyProjector: wrote \(entries.count) entries to \(bibFileURL.lastPathComponent) (missing: \(missing.count), preserved: \(preserved.count))", category: "bib-projector")
        } catch {
            logInfo("BibliographyProjector: write failed: \(error.localizedDescription)", category: "bib-projector")
        }

        // After writing what we have, try to resolve the missing keys via
        // imbib. Resolved keys will be picked up on the next debounce pass.
        if !missing.isEmpty {
            await resolveMissingKeys(missing, bibliography: bibliography, bibFileURL: bibFileURL, source: source)
        }
    }

    /// For each missing cite key, if the document has a cached BibTeX entry
    /// carrying a DOI / arXiv id / bibcode, ask imbib to fetch the paper.
    /// Successful resolves invalidate the publication cache, and the next
    /// debounce pass will see the new row in the local store.
    private func resolveMissingKeys(
        _ missing: [String],
        bibliography: [String: String],
        bibFileURL: URL,
        source: String
    ) async {
        let candidates = missing.filter { key in
            !unresolvableKeys.contains(key) && !inFlightKeys.contains(key)
        }
        guard !candidates.isEmpty else { return }

        var anySucceeded = false
        for key in candidates {
            guard let bibtex = bibliography[key], !bibtex.isEmpty else {
                unresolvableKeys.insert(key)
                continue
            }
            inFlightKeys.insert(key)
            defer { inFlightKeys.remove(key) }

            logInfo("BibliographyProjector: attempting resolve for missing '\(key)'", category: "bib-missing")
            let input = ImbibCitationInput(
                rawBibtex: bibtex,
                freeText: key,
                preferredDatabase: "astronomy"
            )
            let resolution = await CitationClient.shared
                .resolve(citeKey: key, input: input, libraryID: nil)
            switch resolution {
            case .found(let result):
                logInfo("BibliographyProjector: resolved '\(key)' → '\(result.citeKey)'", category: "bib-missing")
                anySucceeded = true
            case .candidates(let list):
                logInfo("BibliographyProjector: '\(key)' needs user pick (\(list.count) candidates)", category: "bib-missing")
                // User must pick in CitedPapersSection — we don't auto-add ambiguous hits.
                unresolvableKeys.insert(key)
            case .notFound(let reason):
                logInfo("BibliographyProjector: '\(key)' unresolvable: \(reason)", category: "bib-missing")
                unresolvableKeys.insert(key)
            }
        }

        // If we auto-added anything, re-run the projection so the new entries
        // land in the .bib file without requiring the user to edit the source.
        if anySucceeded {
            await performUpdate(source: source, bibFileURL: bibFileURL, bibliography: bibliography)
        }
    }

    /// Subscribe to imbib's cross-process store-change notification so that
    /// when the user adds papers in imbib directly, the projector's retry
    /// cache resets and the next update picks them up.
    private func observeLibraryChanges() async {
        let name = NSNotification.Name("storeDidMutate")
        let stream = NotificationCenter.default.notifications(named: name)
        for await _ in stream {
            await clearUnresolvable()
        }
    }

    private func clearUnresolvable() {
        if !unresolvableKeys.isEmpty {
            logInfo("BibliographyProjector: library changed, clearing unresolvable cache (\(unresolvableKeys.count) keys)", category: "bib-missing")
            unresolvableKeys.removeAll()
        }
    }

    /// Extract cite keys from source (runs off main actor).
    private static func extractCiteKeys(from source: String) -> [String] {
        var keys = Set<String>()

        // LaTeX: \cite{key}, \citep{key}, \citet{key}, comma-separated
        let latexPattern = #"\\cite[pt]?\*?\{([^}]+)\}"#
        let latexExt = #"\\(?:cite(?:author|year|alp|alt)?|ref|eqref|pageref|label|autoref|cref|Cref|textcite|parencite|autocite|footcite|smartcite|supercite)\*?\{([^}]+)\}"#

        for pattern in [latexPattern, latexExt] {
            guard let regex = try? NSRegularExpression(pattern: pattern) else { continue }
            let range = NSRange(source.startIndex..., in: source)
            regex.enumerateMatches(in: source, range: range) { match, _, _ in
                guard let m = match, let r = Range(m.range(at: 1), in: source) else { return }
                let keysStr = String(source[r])
                for k in keysStr.components(separatedBy: ",") {
                    let trimmed = k.trimmingCharacters(in: .whitespaces)
                    if !trimmed.isEmpty { keys.insert(trimmed) }
                }
            }
        }

        // Typst: @citeKey
        let typstPattern = #"(?<![a-zA-Z0-9_@])@([a-zA-Z][a-zA-Z0-9_-]*)"#
        if let regex = try? NSRegularExpression(pattern: typstPattern) {
            let range = NSRange(source.startIndex..., in: source)
            regex.enumerateMatches(in: source, range: range) { match, _, _ in
                guard let m = match, let r = Range(m.range(at: 1), in: source) else { return }
                keys.insert(String(source[r]))
            }
        }

        return keys.sorted()
    }

    /// Parse existing .bib file for entries — minimal tokenizer.
    /// Returns (citeKey → raw entry text) for each top-level `@type{key, ...}`.
    private func readExistingEntries(at url: URL) -> [(key: String, entry: String)] {
        guard let data = try? Data(contentsOf: url),
              let text = String(data: data, encoding: .utf8) else {
            return []
        }
        var entries: [(String, String)] = []
        var i = text.startIndex
        while i < text.endIndex {
            guard let at = text[i...].firstIndex(of: "@") else { break }
            guard let openBrace = text[at...].firstIndex(of: "{") else { break }
            let keyStart = text.index(after: openBrace)
            guard let comma = text[keyStart...].firstIndex(of: ",") else { break }
            let citeKey = text[keyStart..<comma].trimmingCharacters(in: .whitespaces)

            var depth = 0
            var endIdx: String.Index? = nil
            var j = openBrace
            while j < text.endIndex {
                let ch = text[j]
                if ch == "{" { depth += 1 }
                else if ch == "}" {
                    depth -= 1
                    if depth == 0 { endIdx = text.index(after: j); break }
                }
                j = text.index(after: j)
            }
            guard let end = endIdx else { break }
            let entry = String(text[at..<end])
            entries.append((citeKey, entry))
            i = end
        }
        return entries
    }

    /// Synthesize a minimal BibTeX entry from a BibliographyRow when the raw
    /// BibTeX isn't stored (unusual — most imbib entries have it).
    private func synthesizeBibTeX(for row: BibliographyRow) -> String {
        var fields: [String] = []
        fields.append("  title = {\(row.title)}")
        if !row.authorString.isEmpty { fields.append("  author = {\(row.authorString)}") }
        if let y = row.year { fields.append("  year = {\(y)}") }
        if let v = row.venue { fields.append("  journal = {\(v)}") }
        if let doi = row.doi { fields.append("  doi = {\(doi)}") }
        return "@article{\(row.citeKey),\n\(fields.joined(separator: ",\n"))\n}"
    }
}
