/// ImploreCore - Swift bindings for implore-core Rust crate
///
/// This package provides Swift access to the Rust visualization engine.
/// The actual bindings are generated by UniFFI and wrapped in ImploreRustCore.
///
/// Available types include:
///
/// Data Types:
/// - Dataset, DatasetSource, DataSchema, DatasetMetadata
/// - FieldDescriptor, DataType, DataProvenance
///
/// View State:
/// - ViewState, Camera3D, CameraProjection
/// - Colormap, ColormapPreset, SelectionBounds
/// - RenderMode, AxisConfig, ShaderValue
///
/// Session Management:
/// - SessionFigure, FigureExport, FigureFormat
///
/// Vector Types:
/// - Vec2f, Vec3f, Vec4f, Vec3d, ColorRgb

import Foundation
@_exported import ImploreRustCore

// MARK: - Swift Extensions

extension Vec3f {
    /// Create from individual components
    public init(_ x: Float, _ y: Float, _ z: Float) {
        self.init(x: x, y: y, z: z)
    }
}

extension ColorRgb {
    /// Create from RGB values (0-255)
    public static func fromRgb255(_ r: UInt8, _ g: UInt8, _ b: UInt8) -> ColorRgb {
        ColorRgb(
            r: Float(r) / 255.0,
            g: Float(g) / 255.0,
            b: Float(b) / 255.0
        )
    }
}

extension DataType {
    /// Check if this is a numeric type suitable for visualization
    public var isNumeric: Bool {
        switch self {
        case .float32, .float64, .int32, .int64:
            return true
        case .bool, .string, .unknown:
            return false
        }
    }
}

extension FigureFormat {
    /// Check if this is a vector format
    public var isVector: Bool {
        switch self {
        case .pdf, .svg, .eps, .typst:
            return true
        case .png:
            return false
        }
    }
}
