//! `SurfaceDemoService` — ADR-0033 D8's demo capability.
//!
//! Generated by `scripts/new-capability.sh surface-demo` and then filled in
//! per `docs/plan-agent-surfaces.md` S9: the scaffold's proof of use. Two
//! verbs, both pure computation over their arguments (no store, no async I/O):
//!
//! - [`series`](SurfaceDemoService::series) — a noisy sine wave: `n` samples
//!   on `[0, 1)` and `sin(2π·freq·x)` plus small deterministic pseudo-noise
//!   (a seeded linear congruential generator — no `rand` dependency — so
//!   [`histogram`](SurfaceDemoService::histogram) over the result is never
//!   degenerate).
//! - [`histogram`](SurfaceDemoService::histogram) — equal-width bins of a
//!   value list, plus a `plot-spec@1.0.0` payload (`crate::plot`) ready for
//!   the `plot` widget.
//!
//! `examples/surface-demo.surface.json` drives both from two sliders (a copy
//! of `crates/impress-surface/examples/signal-explorer.surface.json`, whose
//! verb and argument names already matched these — see that file and this
//! crate's `tests/example_surface.rs`).
//!
//! # Errors, since `#[impress_method]` return types are never `Result`
//!
//! No `#[impress_method]` anywhere in this workspace returns
//! `Result<T, E>` — `impress-service-macros`' generated invoker
//! (`expand_method` in `crates/impress-service-macros/src/lib.rs`) calls the
//! method and hands its output straight to `serde_json::to_value`, with no
//! `?` in between; a `Result`-typed `__out` would just serialize as
//! `{"Ok": …}` / `{"Err": …}`, which would also wrap every *successful*
//! call's shape in a way the plan's worked JSON (and the loop test this
//! crate shares an inventory with) does not expect. So validation failures
//! here follow the pattern already in the workspace for this
//! (`crates/vw-service`'s `ServiceError`, `crates/impress-layout-service`'s
//! `ok`/`message`): an `error: Option<ServiceError>` field, `None` on
//! success and *not serialized at all* then
//! (`skip_serializing_if = "Option::is_none"`), so a successful call's JSON
//! is exactly `{"x": […], "values": […]}` / `{"counts": […], "edges": […],
//! "plot": …}` as specified, and a failed one additionally carries
//! `"error": {"code": …, "message": …}` with empty/null data fields.

use impress_service_core::async_trait;
use impress_service_macros::{impress_service, impress_service_impl};

#[allow(unused_imports)]
use impress_service_macros::impress_method;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;

mod plot;

/// Amplitude of the pseudo-noise `series` adds to its sine wave. Small enough
/// that the signal is still visibly a sine wave, large enough that a
/// `histogram` of it is not a single spike.
const NOISE_AMPLITUDE: f64 = 0.05;

/// Smallest/largest `n` `series` accepts.
const SERIES_N_RANGE: std::ops::RangeInclusive<u32> = 2..=100_000;

/// Smallest/largest `bins` `histogram` accepts.
const HISTOGRAM_BINS_RANGE: std::ops::RangeInclusive<u32> = 1..=1024;

/// One thing wrong with a call's arguments. See the crate docs for why this
/// is a field on the result rather than a `Result` error variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct ServiceError {
    /// Short machine-readable code, kebab-case (e.g. `"invalid-freq"`).
    pub code: String,
    /// Human-readable message.
    pub message: String,
}

impl ServiceError {
    fn new(code: &str, message: impl Into<String>) -> Self {
        ServiceError {
            code: code.to_string(),
            message: message.into(),
        }
    }
}

/// Result of the `series` verb.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SeriesResult {
    /// `n` samples on `[0, 1)`.
    pub x: Vec<f64>,
    /// `sin(2π·freq·x)` plus small deterministic pseudo-noise, one per `x`.
    pub values: Vec<f64>,
    /// Set, and `x`/`values` left empty, when `freq`/`n` failed validation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ServiceError>,
}

impl SeriesResult {
    fn failed(code: &str, message: impl Into<String>) -> Self {
        SeriesResult {
            x: Vec::new(),
            values: Vec::new(),
            error: Some(ServiceError::new(code, message)),
        }
    }
}

/// Result of the `histogram` verb.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct HistogramResult {
    /// One count per bin, `bins` long. Sums to `values.len()`.
    pub counts: Vec<u64>,
    /// Bin boundaries, `bins + 1` long and strictly increasing.
    pub edges: Vec<f64>,
    /// A `plot-spec@1.0.0` payload (`crate::plot`): bin centres against
    /// counts. `Value::Null` when `error` is set.
    pub plot: Value,
    /// Set, and the other fields left empty/null, when `values`/`bins`
    /// failed validation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ServiceError>,
}

impl HistogramResult {
    fn failed(code: &str, message: impl Into<String>) -> Self {
        HistogramResult {
            counts: Vec::new(),
            edges: Vec::new(),
            plot: Value::Null,
            error: Some(ServiceError::new(code, message)),
        }
    }
}

/// A seeded linear congruential generator step, keyed by index `i` — no
/// `rand` dependency (ADR-0033 S9). Deterministic: the same `i` always yields
/// the same value, so `series` is deterministic for a given `(freq, n)`.
/// Constants are the ones `splitmix64` seeds with; only used here to spread
/// bits, not for cryptographic quality.
fn lcg_noise(i: u32) -> f64 {
    const MULT: u64 = 6_364_136_223_846_793_005;
    const INC: u64 = 1_442_695_040_888_963_407;
    const SEED: u64 = 0x2545_F491_4F6C_DD1D;

    let state = SEED
        .wrapping_add(i as u64)
        .wrapping_mul(MULT)
        .wrapping_add(INC);
    // High bits of an LCG are the good ones; low bits cycle short.
    let unit = (state >> 11) as f64 / (1u64 << 53) as f64; // in [0, 1)
    (unit - 0.5) * NOISE_AMPLITUDE
}

/// `SurfaceDemoService` — ADR-0033 D8's demo capability: two pure-computation
/// verbs a surface can call, and the worked example
/// (`examples/surface-demo.surface.json`) driving both from sliders.
#[impress_service]
pub trait SurfaceDemoService: Send + Sync + 'static {
    /// A noisy sine wave: `n` samples `x` on `[0, 1)` and
    /// `values = sin(2π·freq·x) + noise`, `noise` a small deterministic
    /// pseudo-noise term (no `rand` dependency). `n` must be in `2..=100000`
    /// and `freq` must be finite and greater than zero; an invalid call
    /// returns empty `x`/`values` and a populated `error`.
    #[impress_method]
    async fn series(&self, freq: f64, n: u32) -> SeriesResult;

    /// An equal-width histogram of `values` over `bins` buckets spanning
    /// `[min(values), max(values)]`, plus a `plot-spec@1.0.0` payload
    /// (`crate::plot`) of the bin centres against their counts. `bins` must
    /// be in `1..=1024` and `values` must be non-empty and every value
    /// finite; an invalid call returns empty `counts`/`edges`, a null `plot`,
    /// and a populated `error`.
    #[impress_method]
    async fn histogram(&self, values: Vec<f64>, bins: u32) -> HistogramResult;
}

/// The default (and only) implementation: pure computation, no state.
#[derive(Clone, Default)]
pub struct DefaultSurfaceDemoService;

impl DefaultSurfaceDemoService {
    pub fn new() -> Self {
        Self
    }
}

#[async_trait::async_trait]
impl SurfaceDemoService for DefaultSurfaceDemoService {
    async fn series(&self, freq: f64, n: u32) -> SeriesResult {
        if !freq.is_finite() || freq <= 0.0 {
            return SeriesResult::failed(
                "invalid-freq",
                format!("freq must be finite and > 0, got {freq}"),
            );
        }
        if !SERIES_N_RANGE.contains(&n) {
            return SeriesResult::failed(
                "invalid-n",
                format!(
                    "n must be in {}..={}, got {n}",
                    SERIES_N_RANGE.start(),
                    SERIES_N_RANGE.end()
                ),
            );
        }

        let mut x = Vec::with_capacity(n as usize);
        let mut values = Vec::with_capacity(n as usize);
        for i in 0..n {
            let xi = f64::from(i) / f64::from(n);
            let yi = (2.0 * std::f64::consts::PI * freq * xi).sin() + lcg_noise(i);
            x.push(xi);
            values.push(yi);
        }

        SeriesResult {
            x,
            values,
            error: None,
        }
    }

    async fn histogram(&self, values: Vec<f64>, bins: u32) -> HistogramResult {
        if !HISTOGRAM_BINS_RANGE.contains(&bins) {
            return HistogramResult::failed(
                "invalid-bins",
                format!(
                    "bins must be in {}..={}, got {bins}",
                    HISTOGRAM_BINS_RANGE.start(),
                    HISTOGRAM_BINS_RANGE.end()
                ),
            );
        }
        if values.is_empty() {
            return HistogramResult::failed("empty-values", "values must not be empty");
        }
        if values.iter().any(|v| !v.is_finite()) {
            return HistogramResult::failed(
                "non-finite-value",
                "every value must be finite (no NaN/inf)",
            );
        }

        let bins_usize = bins as usize;
        let min = values.iter().cloned().fold(f64::INFINITY, f64::min);
        let max = values.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
        // Equal-width bins need lo < hi; a single repeated value would
        // otherwise give every edge the same coordinate (not monotone).
        let (lo, hi) = if max > min {
            (min, max)
        } else {
            (min - 0.5, min + 0.5)
        };
        let width = (hi - lo) / bins_usize as f64;

        let edges: Vec<f64> = (0..=bins_usize).map(|i| lo + i as f64 * width).collect();

        let mut counts = vec![0u64; bins_usize];
        for v in &values {
            let idx = ((v - lo) / width).floor() as i64;
            let idx = idx.clamp(0, bins_usize as i64 - 1) as usize;
            counts[idx] += 1;
        }

        let bin_centres: Vec<f64> = (0..bins_usize)
            .map(|i| (edges[i] + edges[i + 1]) / 2.0)
            .collect();
        let plot = plot::histogram_plot_spec(&bin_centres, &counts);

        HistogramResult {
            counts,
            edges,
            plot,
            error: None,
        }
    }
}

impress_service_impl! {
    service = SurfaceDemoService,
    impl = DefaultSurfaceDemoService,
    instance = DefaultSurfaceDemoService::new,
    methods = [
        /// A noisy sine wave: `n` samples `x` on `[0, 1)` and `values =
        /// sin(2π·freq·x) + noise`. `n` in `2..=100000`, `freq` finite and
        /// > 0.
        series(freq: f64, n: u32) -> SeriesResult,
        /// An equal-width histogram of `values` over `bins` buckets, plus a
        /// `plot-spec@1.0.0` payload of bin centres against counts.
        histogram(values: Vec<f64>, bins: u32) -> HistogramResult,
    ],
}

#[cfg(test)]
mod tests {
    use super::*;
    use impress_service_core::{runtime, McpToolDescriptor};
    use serde_json::json;

    fn call(name: &str, args: Value) -> Value {
        let tool = McpToolDescriptor::iter()
            .find(|t| t.name == name)
            .unwrap_or_else(|| panic!("{name} should be registered in the inventory"));
        runtime::block_on((tool.handler)(args)).unwrap_or_else(|e| panic!("{name} failed: {e}"))
    }

    // ------------------------------------------------------------- series

    #[test]
    fn series_round_trips_through_the_inventory() {
        let result = call(
            "surface-demo-service_series",
            json!({ "freq": 2.0, "n": 16 }),
        );
        assert_eq!(result["x"].as_array().unwrap().len(), 16);
        assert_eq!(result["values"].as_array().unwrap().len(), 16);
        assert!(result.get("error").is_none());
    }

    #[test]
    fn series_length_matches_n() {
        let service = DefaultSurfaceDemoService::new();
        let result = runtime::block_on(service.series(1.5, 512));
        assert_eq!(result.x.len(), 512);
        assert_eq!(result.values.len(), 512);
        assert!(result.error.is_none());
        // x samples [0, 1): first sample is exactly 0, all samples < 1.
        assert_eq!(result.x[0], 0.0);
        assert!(result.x.iter().all(|&v| (0.0..1.0).contains(&v)));
    }

    #[test]
    fn series_is_deterministic() {
        let service = DefaultSurfaceDemoService::new();
        let a = runtime::block_on(service.series(3.0, 64));
        let b = runtime::block_on(service.series(3.0, 64));
        assert_eq!(a, b);
    }

    #[test]
    fn series_is_not_a_pure_sine_wave() {
        // The whole point of the pseudo-noise: without it, a histogram of a
        // pure sine wave is famously bimodal-with-spikes at the extrema, not
        // a useful demo. Assert the noise term actually perturbs the signal.
        let service = DefaultSurfaceDemoService::new();
        let result = runtime::block_on(service.series(1.0, 32));
        let pure: Vec<f64> = result
            .x
            .iter()
            .map(|&x| (2.0 * std::f64::consts::PI * x).sin())
            .collect();
        assert!(result
            .values
            .iter()
            .zip(pure.iter())
            .any(|(v, p)| (v - p).abs() > 1e-9));
    }

    #[test]
    fn series_rejects_out_of_range_n() {
        let service = DefaultSurfaceDemoService::new();
        let too_small = runtime::block_on(service.series(1.0, 1));
        assert!(too_small.error.is_some());
        assert_eq!(too_small.error.unwrap().code, "invalid-n");

        let too_large = runtime::block_on(service.series(1.0, 100_001));
        assert!(too_large.error.is_some());
    }

    #[test]
    fn series_rejects_non_finite_or_non_positive_freq() {
        let service = DefaultSurfaceDemoService::new();
        for bad in [0.0, -1.0, f64::NAN, f64::INFINITY] {
            let result = runtime::block_on(service.series(bad, 8));
            assert!(
                result.error.is_some(),
                "freq {bad} should have been rejected"
            );
            assert!(result.x.is_empty());
        }
    }

    // ---------------------------------------------------------- histogram

    #[test]
    fn histogram_round_trips_through_the_inventory() {
        let result = call(
            "surface-demo-service_histogram",
            json!({ "values": [0.0, 1.0, 2.0, 3.0], "bins": 4 }),
        );
        assert_eq!(result["counts"].as_array().unwrap().len(), 4);
        assert_eq!(result["edges"].as_array().unwrap().len(), 5);
        assert!(result["plot"].is_object());
        assert!(result.get("error").is_none());
    }

    #[test]
    fn histogram_counts_sum_to_input_length() {
        let service = DefaultSurfaceDemoService::new();
        let series = runtime::block_on(service.series(2.0, 500));
        let result = runtime::block_on(service.histogram(series.values.clone(), 20));
        assert!(result.error.is_none());
        assert_eq!(result.counts.len(), 20);
        assert_eq!(result.edges.len(), 21);
        let total: u64 = result.counts.iter().sum();
        assert_eq!(total, series.values.len() as u64);
    }

    #[test]
    fn histogram_edges_are_monotone() {
        let service = DefaultSurfaceDemoService::new();
        let result = runtime::block_on(service.histogram(vec![1.0, 2.0, 3.0, 100.0], 10));
        assert!(result.error.is_none());
        assert!(result.edges.windows(2).all(|w| w[0] < w[1]));
    }

    #[test]
    fn histogram_handles_degenerate_constant_input() {
        // All values equal: min == max. Edges must still be strictly
        // monotone (the whole reason for the +/-0.5 widening).
        let service = DefaultSurfaceDemoService::new();
        let result = runtime::block_on(service.histogram(vec![5.0; 10], 4));
        assert!(result.error.is_none());
        assert!(result.edges.windows(2).all(|w| w[0] < w[1]));
        assert_eq!(result.counts.iter().sum::<u64>(), 10);
    }

    #[test]
    fn histogram_rejects_empty_values() {
        let service = DefaultSurfaceDemoService::new();
        let result = runtime::block_on(service.histogram(Vec::new(), 10));
        assert!(result.error.is_some());
        assert_eq!(result.error.unwrap().code, "empty-values");
        assert!(result.counts.is_empty());
        assert!(result.plot.is_null());
    }

    #[test]
    fn histogram_rejects_out_of_range_bins() {
        let service = DefaultSurfaceDemoService::new();
        let zero_bins = runtime::block_on(service.histogram(vec![1.0, 2.0], 0));
        assert!(zero_bins.error.is_some());

        let too_many_bins = runtime::block_on(service.histogram(vec![1.0, 2.0], 1025));
        assert!(too_many_bins.error.is_some());
    }

    #[test]
    fn histogram_plot_is_a_plot_spec_shape() {
        let service = DefaultSurfaceDemoService::new();
        let result = runtime::block_on(service.histogram(vec![1.0, 2.0, 3.0, 4.0], 2));
        let plot = result.plot;
        assert_eq!(plot["title"], json!("Histogram"));
        assert_eq!(plot["colormap"], json!("viridis"));
        assert_eq!(plot["strategy"], json!("auto"));
        let series = plot["series"].as_array().expect("series array");
        assert_eq!(series.len(), 1);
        assert_eq!(series[0]["kind"], json!("line"));
        assert_eq!(series[0]["xs"].as_array().unwrap().len(), 2);
        assert_eq!(series[0]["ys"].as_array().unwrap().len(), 2);
    }
}
