//! The task-local call context (plan-self-reflective-layer H-P2-1, H-P2-2,
//! H-P2-3).
//!
//! The pipeline sets one [`CallContext`] around the handler step of every
//! call. Anything that runs *inside* the call — the verb, the store it
//! writes, a nested verb a surface's `call` effect runs — reads it with
//! [`current`]:
//!
//! * the store stamps `batch_id = call_id` on every `OperationSpec` written
//!   with no batch of its own, so "why did this item change" is a join;
//! * a nested call inherits the caller and the trace and records the outer
//!   call as its `parent_call`, so one trace id joins a surface click, its
//!   verb, and the verbs the surface ran;
//! * `store_override` is the per-call store a Tier A scenario runs against
//!   ([`super::invoke_on`]); the process-wide store stays the default.
//!
//! A task-local, not a thread-local: a handler is an `async` future that
//! may move between the runtime's worker threads. A future spawned with
//! `tokio::spawn` or `spawn_blocking` does not inherit it, which is the
//! documented limit — a verb that spawns its writes onto another task is
//! recorded as having written nothing, and the audit row says so by its
//! `ops` count.

use std::any::Any;
use std::sync::Arc;

use super::identity::CallerIdentity;

/// What every call runs under.
#[derive(Debug, Clone)]
pub struct CallContext {
    /// This call's id: the `core/verb-call@1.0.0` row's id and the
    /// `batch_id` of every operation the verb wrote.
    pub call_id: String,
    /// The trace this call belongs to; generated by the pipeline when the
    /// entry path carried none, inherited by every nested call.
    pub trace_id: String,
    /// The call this one ran inside, when it did.
    pub parent_call: Option<String>,
    /// Who is calling, as the transport established it.
    pub caller: CallerIdentity,
    /// The verb being run.
    pub verb: &'static str,
    /// The store this call runs against instead of the process-wide one.
    /// Type-erased because this crate is on the kit's pure tier and cannot
    /// name `SqliteItemStore`; [`store_override`] downcasts it.
    pub store_override: Option<Arc<dyn Any + Send + Sync>>,
}

tokio::task_local! {
    static CURRENT: Arc<CallContext>;
}

/// The context of the call this code is running inside, if any.
pub fn current() -> Option<Arc<CallContext>> {
    CURRENT.try_with(Arc::clone).ok()
}

/// The current call's id — what the store stamps as `batch_id`.
pub fn current_call_id() -> Option<String> {
    CURRENT.try_with(|c| c.call_id.clone()).ok()
}

/// The store the current call was told to use, when it was told one.
pub fn store_override<T: Any + Send + Sync>() -> Option<Arc<T>> {
    let erased = CURRENT
        .try_with(|c| c.store_override.clone())
        .ok()
        .flatten()?;
    erased.downcast::<T>().ok()
}

/// Run `future` with `context` current.
pub async fn scope<F: std::future::Future>(context: Arc<CallContext>, future: F) -> F::Output {
    CURRENT.scope(context, future).await
}

/// Run `work` with `context` current, synchronously — the FFI's layout
/// `apply`, which is a sync call from Swift.
pub fn sync_scope<T>(context: Arc<CallContext>, work: impl FnOnce() -> T) -> T {
    CURRENT.sync_scope(context, work)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn context(id: &str) -> Arc<CallContext> {
        Arc::new(CallContext {
            call_id: id.to_string(),
            trace_id: "t".to_string(),
            parent_call: None,
            caller: CallerIdentity::Person,
            verb: "x-service_y",
            store_override: None,
        })
    }

    #[test]
    fn nothing_is_current_outside_a_call() {
        assert!(current().is_none());
        assert!(current_call_id().is_none());
        assert!(store_override::<String>().is_none());
    }

    #[test]
    fn a_sync_scope_is_visible_inside_and_gone_after() {
        let seen = sync_scope(context("c1"), current_call_id);
        assert_eq!(seen.as_deref(), Some("c1"));
        assert!(current_call_id().is_none());
    }

    #[tokio::test]
    async fn an_async_scope_survives_awaits() {
        let seen = scope(context("c2"), async {
            tokio::task::yield_now().await;
            current_call_id()
        })
        .await;
        assert_eq!(seen.as_deref(), Some("c2"));
    }

    #[test]
    fn the_store_override_downcasts_to_its_type_and_nothing_else() {
        let mut ctx = (*context("c3")).clone();
        ctx.store_override = Some(Arc::new(42u64) as Arc<dyn Any + Send + Sync>);
        sync_scope(Arc::new(ctx), || {
            assert_eq!(store_override::<u64>().as_deref(), Some(&42));
            assert!(store_override::<String>().is_none());
        });
    }
}
