//! The task-local call context (plan-self-reflective-layer H-P2-1, H-P2-2,
//! H-P2-3).
//!
//! The pipeline sets one [`CallContext`] around the handler step of every
//! call. Anything that runs *inside* the call — the verb, the store it
//! writes, a nested verb a surface's `call` effect runs — reads it with
//! [`current`]:
//!
//! * the store stamps `batch_id = call_id` on every `OperationSpec` written
//!   with no batch of its own, so "why did this item change" is a join;
//! * a nested call inherits the caller and the trace and records the outer
//!   call as its `parent_call`, so one trace id joins a surface click, its
//!   verb, and the verbs the surface ran;
//! * `store_override` is the per-call store a Tier A scenario runs against
//!   ([`super::invoke_on`]); the process-wide store stays the default.
//!
//! A task-local, not a thread-local: a handler is an `async` future that
//! may move between the runtime's worker threads. A future spawned with
//! `tokio::spawn` or `spawn_blocking` does not inherit it, which is the
//! documented limit — a verb that spawns its writes onto another task is
//! recorded as having written nothing, and the audit row says so by its
//! `ops` count.

use std::any::Any;
use std::cell::RefCell;
use std::collections::BTreeSet;
use std::sync::{Arc, Mutex};

use super::identity::CallerIdentity;

/// Created and deleted item ids observed while one handler runs. Each call
/// gets its own instance, including a call nested inside another handler.
#[derive(Debug, Clone, Default)]
pub struct MutationIds(Arc<Mutex<MutationIdSets>>);

#[derive(Debug, Default)]
struct MutationIdSets {
    inserted: BTreeSet<String>,
    deleted: BTreeSet<String>,
}

impl MutationIds {
    fn note(&self, id: String, created: bool, deleted: bool) {
        if !created && !deleted {
            return;
        }
        let mut ids = self
            .0
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        if created {
            ids.inserted.insert(id.clone());
        }
        if deleted {
            ids.deleted.insert(id);
        }
    }

    /// A stable, deduplicated snapshot for the audit record.
    pub fn snapshot(&self) -> (Vec<String>, Vec<String>) {
        let ids = self
            .0
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        (
            ids.inserted.iter().cloned().collect(),
            ids.deleted.iter().cloned().collect(),
        )
    }
}

/// What every call runs under.
#[derive(Debug, Clone)]
pub struct CallContext {
    /// This call's id: the `core/verb-call@1.0.0` row's id and the
    /// `batch_id` of every operation the verb wrote.
    pub call_id: String,
    /// The trace this call belongs to; generated by the pipeline when the
    /// entry path carried none, inherited by every nested call.
    pub trace_id: String,
    /// The call this one ran inside, when it did.
    pub parent_call: Option<String>,
    /// Who is calling, as the transport established it.
    pub caller: CallerIdentity,
    /// The verb being run.
    pub verb: &'static str,
    /// The store this call runs against instead of the process-wide one.
    /// Type-erased because this crate is on the kit's pure tier and cannot
    /// name `SqliteItemStore`; [`store_override`] downcasts it.
    pub store_override: Option<Arc<dyn Any + Send + Sync>>,
    /// Item creations and deletions observed during this call only.
    pub mutation_ids: MutationIds,
}

tokio::task_local! {
    static CURRENT: Arc<CallContext>;
    static REPORTED_REFUSAL: RefCell<Option<crate::refusal::Refusal>>;
}

/// Preserve a native backend failure when an existing service method returns
/// a primitive or `Option` rather than `Result`. Its typed placeholder never
/// escapes the pipeline: the handler step replaces it with this refusal before
/// envelope handling and audit. Keep the first failure, and isolate nested calls.
pub fn report_refusal(code: impl Into<String>, message: impl Into<String>) {
    let refusal = crate::refusal::Refusal::new(code, message);
    if REPORTED_REFUSAL
        .try_with(|slot| {
            slot.borrow_mut().get_or_insert(refusal);
        })
        .is_err()
    {
        tracing::error!("native backend refusal reported outside the invoker pipeline");
    }
}

pub(crate) fn take_reported_refusal() -> Option<crate::refusal::Refusal> {
    REPORTED_REFUSAL
        .try_with(|slot| slot.borrow_mut().take())
        .ok()
        .flatten()
}

/// The context of the call this code is running inside, if any.
pub fn current() -> Option<Arc<CallContext>> {
    CURRENT.try_with(Arc::clone).ok()
}

/// The current call's id — what the store stamps as `batch_id`.
pub fn current_call_id() -> Option<String> {
    CURRENT.try_with(|c| c.call_id.clone()).ok()
}

/// Record a store mutation in the current call, if there is one. The store
/// invokes this only after a successful mutation has been committed.
pub fn note_mutation(id: String, created: bool, deleted: bool) {
    let _ = CURRENT.try_with(|context| context.mutation_ids.note(id, created, deleted));
}

/// The store the current call was told to use, when it was told one.
pub fn store_override<T: Any + Send + Sync>() -> Option<Arc<T>> {
    let erased = CURRENT
        .try_with(|c| c.store_override.clone())
        .ok()
        .flatten()?;
    erased.downcast::<T>().ok()
}

/// Run `future` with `context` current.
pub async fn scope<F: std::future::Future>(context: Arc<CallContext>, future: F) -> F::Output {
    REPORTED_REFUSAL
        .scope(RefCell::new(None), CURRENT.scope(context, future))
        .await
}

/// Run `work` with `context` current, synchronously — the FFI's layout
/// `apply`, which is a sync call from Swift.
pub fn sync_scope<T>(context: Arc<CallContext>, work: impl FnOnce() -> T) -> T {
    REPORTED_REFUSAL.sync_scope(RefCell::new(None), || CURRENT.sync_scope(context, work))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn context(id: &str) -> Arc<CallContext> {
        Arc::new(CallContext {
            call_id: id.to_string(),
            trace_id: "t".to_string(),
            parent_call: None,
            caller: CallerIdentity::Person,
            verb: "x-service_y",
            store_override: None,
            mutation_ids: MutationIds::default(),
        })
    }

    #[test]
    fn nothing_is_current_outside_a_call() {
        assert!(current().is_none());
        assert!(current_call_id().is_none());
        assert!(store_override::<String>().is_none());
    }

    #[test]
    fn a_sync_scope_is_visible_inside_and_gone_after() {
        let seen = sync_scope(context("c1"), current_call_id);
        assert_eq!(seen.as_deref(), Some("c1"));
        assert!(current_call_id().is_none());
    }

    #[tokio::test]
    async fn an_async_scope_survives_awaits() {
        let seen = scope(context("c2"), async {
            tokio::task::yield_now().await;
            current_call_id()
        })
        .await;
        assert_eq!(seen.as_deref(), Some("c2"));
    }

    #[test]
    fn the_store_override_downcasts_to_its_type_and_nothing_else() {
        let mut ctx = (*context("c3")).clone();
        ctx.store_override = Some(Arc::new(42u64) as Arc<dyn Any + Send + Sync>);
        sync_scope(Arc::new(ctx), || {
            assert_eq!(store_override::<u64>().as_deref(), Some(&42));
            assert!(store_override::<String>().is_none());
        });
    }

    #[tokio::test]
    async fn nested_and_concurrent_calls_keep_their_mutation_ids_separate() {
        let outer = context("outer");
        let concurrent = context("concurrent");
        let concurrent_result = tokio::spawn(scope(concurrent.clone(), async move {
            note_mutation("concurrent-id".into(), true, false);
            tokio::task::yield_now().await;
            concurrent.mutation_ids.snapshot()
        }));

        scope(outer.clone(), async {
            note_mutation("outer-id".into(), true, false);
            let inner = context("inner");
            scope(inner.clone(), async {
                note_mutation("inner-id".into(), false, true);
                note_mutation("inner-id".into(), false, true);
                tokio::task::yield_now().await;
            })
            .await;
            assert_eq!(
                inner.mutation_ids.snapshot(),
                (vec![], vec!["inner-id".into()])
            );
            note_mutation("outer-id".into(), true, false);
        })
        .await;

        assert_eq!(
            outer.mutation_ids.snapshot(),
            (vec!["outer-id".into()], vec![])
        );
        assert_eq!(
            concurrent_result.await.unwrap(),
            (vec!["concurrent-id".into()], vec![])
        );
        note_mutation("outside".into(), true, true);
        assert_eq!(
            outer.mutation_ids.snapshot(),
            (vec!["outer-id".into()], vec![])
        );
    }
}
