//
//  ManuscriptTypes.swift
//  PublicationManagerCore
//
//  Created by Claude on 2026-01-19.
//

import Foundation
import SwiftUI

// MARK: - Manuscript Status (ADR-021)

/// Status of a manuscript in the publication workflow.
///
/// Tracks the progression from initial drafting through publication.
public enum ManuscriptStatus: String, Codable, CaseIterable, Sendable {
    case drafting = "drafting"
    case submitted = "submitted"
    case underReview = "under_review"
    case revision = "revision"
    case accepted = "accepted"
    case published = "published"
    case rejected = "rejected"

    /// Human-readable display name
    public var displayName: String {
        switch self {
        case .drafting: return "Drafting"
        case .submitted: return "Submitted"
        case .underReview: return "Under Review"
        case .revision: return "In Revision"
        case .accepted: return "Accepted"
        case .published: return "Published"
        case .rejected: return "Rejected"
        }
    }

    /// SF Symbol for this status
    public var systemImage: String {
        switch self {
        case .drafting: return "pencil"
        case .submitted: return "paperplane"
        case .underReview: return "eye"
        case .revision: return "arrow.triangle.2.circlepath"
        case .accepted: return "checkmark.circle"
        case .published: return "book.closed"
        case .rejected: return "xmark.circle"
        }
    }

    /// Color for this status
    public var color: Color {
        switch self {
        case .drafting: return .gray
        case .submitted: return .blue
        case .underReview: return .orange
        case .revision: return .purple
        case .accepted: return .green
        case .published: return .green
        case .rejected: return .red
        }
    }

    /// Whether this is an "active" status (still in progress)
    public var isActive: Bool {
        switch self {
        case .drafting, .submitted, .underReview, .revision:
            return true
        case .accepted, .published, .rejected:
            return false
        }
    }

    /// Whether this is a "completed" status (successfully finished)
    public var isCompleted: Bool {
        switch self {
        case .accepted, .published:
            return true
        default:
            return false
        }
    }

    /// Sort order for display (active first, then completed, then rejected)
    public var sortOrder: Int {
        switch self {
        case .drafting: return 0
        case .submitted: return 1
        case .underReview: return 2
        case .revision: return 3
        case .accepted: return 4
        case .published: return 5
        case .rejected: return 6
        }
    }
}

// MARK: - Bibliography Mode

/// How the manuscript's bibliography is managed.
public enum BibliographyMode: String, Codable, CaseIterable, Sendable {
    case manual = "manual"
    /// User manages .bib externally; imbib can import changes

    case autoGenerated = "auto_generated"
    /// imbib generates .bib from cited publications automatically

    case watched = "watched"
    /// imbib watches an external .bib and imports new entries

    /// Human-readable display name
    public var displayName: String {
        switch self {
        case .manual: return "Manual"
        case .autoGenerated: return "Auto-Generated"
        case .watched: return "Watched File"
        }
    }

    /// Description for UI
    public var description: String {
        switch self {
        case .manual:
            return "Manage your .bib file externally"
        case .autoGenerated:
            return "imbib generates .bib from cited papers"
        case .watched:
            return "imbib imports changes from external .bib"
        }
    }
}

// MARK: - Manuscript Attachment Tags

/// Predefined tag names for manuscript-related attachments.
///
/// These tags help organize different versions and documents
/// associated with a manuscript.
public enum ManuscriptAttachmentTag: String, CaseIterable, Sendable {
    // Submission versions
    case submissionV1 = "manuscript:submission-v1"
    case submissionV2 = "manuscript:submission-v2"
    case submissionV3 = "manuscript:submission-v3"

    // Revision rounds
    case revisionR1 = "manuscript:revision-r1"
    case revisionR2 = "manuscript:revision-r2"
    case revisionR3 = "manuscript:revision-r3"

    // Review documents
    case refereeReport = "manuscript:referee-report"
    case responseLetter = "manuscript:response-letter"

    // Final versions
    case finalAccepted = "manuscript:final-accepted"
    case published = "manuscript:published"
    case proofs = "manuscript:proofs"

    // Supporting materials
    case supplementary = "manuscript:supplementary"
    case coverLetter = "manuscript:cover-letter"

    /// The common prefix for all manuscript tags
    public static let prefix = "manuscript:"

    /// Human-readable display name
    public var displayName: String {
        switch self {
        case .submissionV1: return "Submission v1"
        case .submissionV2: return "Submission v2"
        case .submissionV3: return "Submission v3"
        case .revisionR1: return "Revision R1"
        case .revisionR2: return "Revision R2"
        case .revisionR3: return "Revision R3"
        case .refereeReport: return "Referee Report"
        case .responseLetter: return "Response Letter"
        case .finalAccepted: return "Final Accepted"
        case .published: return "Published Version"
        case .proofs: return "Proofs"
        case .supplementary: return "Supplementary Material"
        case .coverLetter: return "Cover Letter"
        }
    }

    /// SF Symbol for this tag type
    public var systemImage: String {
        switch self {
        case .submissionV1, .submissionV2, .submissionV3:
            return "doc.badge.arrow.up"
        case .revisionR1, .revisionR2, .revisionR3:
            return "doc.badge.ellipsis"
        case .refereeReport:
            return "text.bubble"
        case .responseLetter:
            return "arrowshape.turn.up.left"
        case .finalAccepted:
            return "checkmark.seal"
        case .published:
            return "book.closed"
        case .proofs:
            return "doc.text.magnifyingglass"
        case .supplementary:
            return "doc.on.doc"
        case .coverLetter:
            return "envelope"
        }
    }

    /// Color for this tag type
    public var color: Color {
        switch self {
        case .submissionV1, .submissionV2, .submissionV3:
            return .blue
        case .revisionR1, .revisionR2, .revisionR3:
            return .purple
        case .refereeReport:
            return .orange
        case .responseLetter:
            return .teal
        case .finalAccepted:
            return .green
        case .published:
            return .green
        case .proofs:
            return .yellow
        case .supplementary:
            return .gray
        case .coverLetter:
            return .indigo
        }
    }

    /// Whether this is a version tag (submission or revision)
    public var isVersionTag: Bool {
        switch self {
        case .submissionV1, .submissionV2, .submissionV3,
             .revisionR1, .revisionR2, .revisionR3:
            return true
        default:
            return false
        }
    }

    /// Create a submission tag for a specific version number
    public static func submission(version: Int) -> String {
        "\(prefix)submission-v\(version)"
    }

    /// Create a revision tag for a specific round number
    public static func revision(round: Int) -> String {
        "\(prefix)revision-r\(round)"
    }

    /// Check if a tag name is a manuscript tag
    public static func isManuscriptTag(_ tagName: String) -> Bool {
        tagName.hasPrefix(prefix)
    }

    /// Parse a tag name to get version/round number if applicable
    public static func parseVersionNumber(from tagName: String) -> Int? {
        guard isManuscriptTag(tagName) else { return nil }

        // Try to extract number from patterns like "submission-v1" or "revision-r2"
        let patterns = [
            "submission-v(\\d+)",
            "revision-r(\\d+)"
        ]

        for pattern in patterns {
            if let regex = try? NSRegularExpression(pattern: pattern),
               let match = regex.firstMatch(in: tagName, range: NSRange(tagName.startIndex..., in: tagName)),
               match.numberOfRanges > 1,
               let range = Range(match.range(at: 1), in: tagName) {
                return Int(tagName[range])
            }
        }

        return nil
    }
}

// MARK: - Manuscript Metadata Keys

/// Keys used to store manuscript metadata in rawFields.
///
/// All keys are prefixed with underscore to avoid collision with
/// standard BibTeX fields.
public enum ManuscriptMetadataKey: String, Sendable {
    case status = "_manuscript_status"
    case venue = "_submission_venue"
    case revisionNumber = "_revision_number"
    case notes = "_manuscript_notes"
    case citedPublicationIDs = "_cited_publication_ids"
    case bibliographyMode = "_bibliography_mode"
    case externalBibPath = "_external_bib_path"
    case submissionDate = "_submission_date"
    case acceptanceDate = "_acceptance_date"
    case targetJournal = "_target_journal"
    case coauthorEmails = "_coauthor_emails"
}
